#ifndef HEADERS_FUNCTIONS_OVERLAY11_H_
#define HEADERS_FUNCTIONS_OVERLAY11_H_

struct c_ranger_net_scene* CRangerNetSceneConstructor(struct c_ranger_net_scene* this,
                                                      struct megastruct* param_2);
void CRangerNetSceneInit(struct c_ranger_net_scene* param_1);
void ret_0211d860(void);
struct c_ranger_net_agb_scene* CRangerNetAgbSceneConstructor(struct c_ranger_net_agb_scene* this);
void ret_0211df48(void);
void ret_0211df4c(void);
void ret_0211df50(void);
void ret_0211df58(void);
void ret_0211df5c(void);
void ret_0211df60(void);
struct ov_11_unk_struct_0x730* Ov110x730Constructor(struct ov_11_unk_struct_0x730* this,
                                                    struct megastruct* megastruct_ptr, int param_3);
void Ov110x730InitPrimary(struct ov_11_unk_struct_0x730* this);
void Ov110x730InitSecondaryVeneer(struct ov_11_unk_struct_0x730* this);
void Ov110x730InitSecondary(struct ov_11_unk_struct_0x730* param_1);
void Ov110x730Destructor(struct ov_11_unk_struct_0x730* param_1);
void ret_021245a4(void);
int Return0x2700(void);
void ret_02126964(void);
void ret_02126968(void);
void ret_0212697c(void);
void ret_02126980(void);
void ret_02126984(void);
struct ov_11_unk_struct_0x3ec* Ov110x3ecConstructor(struct ov_11_unk_struct_0x3ec* this,
                                                    struct megastruct* megastruct_ptr,
                                                    struct ov_11_unk_struct_0x730* parent);
int MaybeInitRsaKeyFileData(int param_1, char* param_2, undefined4 param_3, undefined4 param_4);
void ret_0212d978(void);
struct ov_11_unk_struct_0x198* Ov110x198Constructor(struct ov_11_unk_struct_0x198* this,
                                                    struct ov_11_unk_struct_0x730* parent);
struct ov_11_unk_struct_0x18* Ov110x18Constructor(struct ov_11_unk_struct_0x18* param_1,
                                                  struct megastruct* megastruct_ptr);
struct ov_11_unk_struct_0x4e4* Ov110x4e4Constructor(struct ov_11_unk_struct_0x4e4* param_1,
                                                    struct megastruct* megastruct_ptr_ptr,
                                                    struct ov_11_unk_struct_0x18* param_3,
                                                    struct ov_11_unk_struct_0x730* param_4);
struct ov_11_unk_struct_2* Overlay11EntryPoint2(struct ov_11_unk_struct_2* param_1);
void ret_0213201c(void);
void ret_02132020(void);
undefined4 Dwc_AC_Process(void);
void Dwc_AC_GetStatus(void);
undefined1 Dwc_AC_GetApType(void);
undefined4 Dwc_AC_Destroy(void);
void Dwci_AC_InsertApInfo(int param_1, undefined4 param_2);
void Dwci_AC_Alloc(unsigned int param_1, undefined4 param_2);
struct unk_wifi_struct_0x18* Dwci_AC_GetMemPtr(unsigned int param_1);
void Dwci_AC_SetPhase(unsigned int param_1);
undefined1 MaybeGetWfcInitCase(void);
void Dwci_AC_SetError(undefined4 param_1);
undefined4 Dwci_AC_GetError(void);
unsigned int Dwci_ConvConnectApType(unsigned int param_1);
void Free_Disused(void);
undefined4 CheckDuplicate(void);
undefined4 Dwci_AC_CheckNintendoSsid(int param_1);
unsigned int CompareList(int param_1, int param_2, int param_3);
unsigned int CompareListDiff(int param_1, int param_2);
int AddList(undefined1 param_1, int param_2, undefined4 param_3, int param_4);
void SetDataListTail(undefined1 param_1, int param_2, int8_t param_3, int param_4);
void UpDateList(int param_1, int param_2, int8_t param_3, int param_4);
void SortList(int param_1, int param_2);
void Dwci_AC_CallBackWcm(int16_t* param_1);
int Dwci_AC_ConnectAP(void);
undefined4 ConnectStart(int param_1);
undefined4 ConnectAP(int param_1);
unsigned int GetConnectType(int param_1);
undefined4 GetPowerMode(int param_1);
undefined4 GetAuthMode(int param_1);
undefined4 Dwci_AC_CloseNetwork(int8_t* param_1);
undefined4 DisConnectAP(void);
bool CloseSocket(void);
undefined4 Dwci_AC_Error(void);
void Dwci_AC_GetResult(void);
undefined4 GetProgramaError(undefined4 param_1);
undefined4 GetNotFoundAP(int param_1);
undefined1 Dwci_AC_MakeSearchList(int param_1);
undefined4 Dwci_AC_CheckFreespot(int param_1);
unsigned int MakeAroundList(int param_1);
unsigned int MakeStealthList(int param_1);
char MakeUserList(int param_1);
char MakeDifferChannelList(int param_1);
unsigned int CheckDifferChannelStart(int param_1);
int8_t Dwci_AC_ConnectRetryAP(void);
int Dwci_AC_SearchAP(void);
void Dwci_AC_SetStealthChannel(unsigned int param_1);
int Dwci_AC_GetStealthChannel(unsigned int param_1);
void Dwci_AC_SearchReStart(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
undefined4 SearchStart(int param_1);
undefined4 SearchAround(int param_1);
undefined4 SearchAround2ndLap(int param_1);
undefined4 SearchDifferChannel(int param_1);
undefined4 SearchStealth(int param_1);
int NextSearchCheck(int param_1, int param_2);
int SearchEndCheck(unsigned int param_1, int param_2);
undefined4 CheckStartStealthSearch(int param_1);
void ScanStart(undefined4 param_1, undefined4 param_2, int param_3, unsigned int param_4);
undefined4 Dwci_AC_Start(void);
int Dwci_AC_ConnectTest(void);
undefined4 ConnectTestStart(undefined4 param_1);
undefined4 GetIpAddress(int param_1);
undefined4 ConnectTestCreate(void);
undefined4 ConnectTestProcess(int param_1);
undefined4 ConnectTestEnd(int param_1);
undefined4 ConnectTestRetry(void);
void MakeSocConfig(undefined4* param_1, int param_2, undefined4* param_3);
unsigned int ConvAddress(int8_t* param_1);
unsigned int ConvNetMask(int param_1);
void CheckSetDns(int param_1);
bool Dwci_AC_CheckNintendoShopAP(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                                 undefined4 param_4);
void Dwci_AC_GetNintendoShopWepKey(undefined4 param_1, undefined4 param_2);
void Dwci_AC_GetPostalCode(undefined4 param_1, undefined4* param_2);
bool Dwci_AC_CheckNintendoUsbAP(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                                undefined4 param_4);
void DecodeSsid(undefined4 param_1, int param_2, undefined4 param_3, undefined4 param_4);
void MakeShopWepKey(undefined4 param_1, undefined4* param_2);
void MakeUsbWepKey(int param_1, undefined4* param_2);
int Codetovalue(unsigned int param_1);
unsigned int Db64(int param_1, int param_2, unsigned int param_3, unsigned int param_4);
void Dwc_Auth_SetCustomNas(char* param_1);
int Dwc_Auth_Create(undefined4* param_1, undefined4 param_2, undefined4 param_3,
                    undefined4 param_4);
void Dwci_Auth_StartThread(void);
void Dwc_Auth_Abort(undefined4 param_1, int param_2);
void Dwc_Auth_Destroy(void);
undefined4 Dwc_Auth_GetError(undefined4 param_1, int param_2);
void Dwc_Auth_GetResult(int* param_1);
undefined4 Dwci_Auth_Start(int param_1);
void Dwci_Auth_Thread(void);
undefined4 Dwci_Auth_ParseHttp(void);
undefined4 Dwci_Auth_FillResult(void);
undefined4 Dwci_Auth_Prepare_FirstPost(undefined4 param_1, char* param_2, undefined4 param_3,
                                       undefined4 param_4);
void Dwci_Auth_SetError(undefined4 param_1);
void Dwc_Auth_GetCalInfoFromNVram(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                                  undefined4 param_4);
bool Dwc_Auth_SetCalInfoToHttp(undefined4 param_1, char* param_2, int param_3);
undefined4 Dwc_Http_Create(int8_t* param_1, undefined4* param_2);
undefined4 Dwc_Http_FinishHeader(int param_1);
void Dwc_Http_StartThread(int param_1, undefined4 param_2);
void Dwc_Http_Abort(int param_1, int param_2);
undefined4 Dwci_Http_Yield(int param_1, int param_2);
void Dwci_Http_InitCpsSocket(int param_1);
void Dwci_Http_Resolve(int param_1);
undefined4 Dwci_Http_CheckHeaderReceived(int param_1);
void Dwci_Http_Thread(int param_1);
void Dwc_Http_Destroy(int8_t* param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
undefined4 Dwci_Http_WriteBasicHeader(int param_1);
undefined4 Dwc_Http_Add_HeaderItem(int param_1, char* param_2, char* param_3);
undefined4 Dwc_Http_Add_PostBase64Item(int param_1, char* param_2, undefined4 param_3,
                                       undefined4 param_4);
undefined4 Dwc_Http_Add_Body(int param_1, char* param_2, undefined4 param_3, undefined4 param_4);
undefined4 Dwci_Http_AllocBuffer(int param_1, int* param_2, int param_3, undefined4 param_4);
void Dwci_Http_FreeBuffer(int param_1, int* param_2);
undefined4 Dwci_Http_ReallocBuffer(int param_1, int* param_2, int param_3, undefined4 param_4);
undefined4 Dwci_Http_SetHostinfo(int param_1, char* param_2);
undefined4 Dwci_Http_AddResult(int param_1, int* param_2, char* param_3, char* param_4);
undefined4 Dwc_Http_ParseResult(int param_1, int param_2, undefined4 param_3, undefined4 param_4);
undefined4 Dwc_Http_GetResult(int param_1, char* param_2);
void Dwc_Http_GetBase64DecodedResult(undefined4 param_1, undefined4 param_2, int param_3,
                                     unsigned int param_4);
undefined4 Dwc_Http_GetRawResult(undefined4 param_1, undefined4 param_2, char* param_3,
                                 int param_4);
void Dwci_Http_DestroyResult(int param_1, int param_2, int param_3);
undefined4 Dwc_Netcheck_Create(undefined4* param_1, undefined4 param_2, undefined4 param_3,
                               undefined4 param_4);
void Dwc_Netcheck_Destroy(void);
void Dwc_Netcheck_Abort(void);
undefined4 Dwc_Netcheck_GetError(undefined4 param_1, int param_2);
undefined4 Dwc_Netcheck_GetReturnCode(void);
void Dwci_Netcheck_StartThread(void);
void Dwci_Netcheck_SetError(undefined4 param_1);
undefined4 Dwc_Auth_SetNasTimeDiff(char* param_1, undefined4 param_2, undefined4 param_3,
                                   undefined4 param_4);
undefined4 Dwc_Svl_Init(void** param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwc_Svl_Cleanup(void);
undefined4 Dwc_Svl_GetTokenAsync(undefined4 param_1, int8_t* param_2, undefined4 param_3,
                                 undefined4 param_4);
undefined4 Dwc_Svl_Process(void);
undefined4 Dwci_Svl_ParseHttp(void);
unsigned int Dwc_Auth_Base64Encode(undefined4* param_1, unsigned int param_2, int param_3,
                                   unsigned int param_4);
int8_t* Dwc_Auth_Base64Decode(int param_1, unsigned int param_2, int8_t* param_3, int8_t* param_4);
void Dwci_BM_GetWiFiInfo(undefined4* param_1);
bool Dwci_BM_SetWiFiInfo(undefined4 param_1, int param_2);
undefined4 Dwci_BackuplInit(uint16_t* param_1);
bool Dwci_BackuplRead(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                      undefined4 param_4);
bool Dwci_BackuplWritePage(int param_1, int param_2, undefined4 param_3);
bool Dwci_BackuplWriteAll(int param_1);
void Dwci_BackuplSetWiFi(undefined4* param_1);
char Dwci_BackuplConvMaskCidr(int param_1);
void Dwci_BackuplConvMaskAddr(unsigned int param_1, int param_2);
undefined4 Dwc_BackuplCheckSsid(int param_1);
bool Dwc_BackuplCheckIp(undefined4* param_1, undefined4* param_2, undefined4 param_3,
                        undefined4 param_4);
bool Dwc_BackuplCheckAddress(int8_t* param_1);
bool Verify(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
uint16_t Callback_NVram(undefined4 param_1, uint16_t param_2, int param_3);
undefined* Dwci_BackuplConvWifiInfo(undefined4* param_1);
undefined4 Dwc_BM_Init(int8_t* param_1);
undefined4 CheckAp(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
undefined4 Init(int16_t* param_1);
void InitPage(int param_1, int param_2);
unsigned long long Dwci_Util_WiFiId_ScrambleUid(unsigned int param_1, unsigned int param_2,
                                                unsigned int param_3, unsigned int param_4);
undefined4 Dwci_Auth_GetNewWiFiInfo(undefined4* param_1);
bool Dwci_Auth_MakeWiFiID(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                          undefined4 param_4);
bool Dwci_Auth_UpDateWiFiID(undefined4* param_1, undefined4 param_2);
undefined4 Dwci_Auth_RemakeWiFiID(int param_1);
bool Dwc_Auth_CheckWiFiIdNeedCreate(void);
undefined4 Dwc_GetLastError(undefined4* param_1);
undefined4 Dwc_GetLastErrorEx(undefined4* param_1, undefined4* param_2);
bool Dwci_IsError(void);
void Dwci_SetError(int param_1, undefined4 param_2);
void Dwc_InitInetEx(struct DWCInetControl* inetCntl, uint16_t dmaNo, uint16_t powerMode,
                    uint16_t ssl_priority);
void Dwc_InitInet(struct DWCInetControl* inetCntl);
void Dwc_SetAuthServer(int param_1);
bool Dwc_CheckInet(void);
void Dwc_ProcessInet(void);
undefined4 Dwc_GetInetStatus(void);
void Dwc_CleanupInet(void);
undefined4 Dwc_CleanupInetAsync(void);
undefined4 Dwci_CheckDisconnected(void);
void Wcm_GetLinkLevelVeneer(void);
undefined4 Dwc_UpdateConnection(void);
undefined4 Dwc_SvlgetTokenAsync(char* param_1, undefined4 param_2, undefined4 param_3,
                                undefined4 param_4);
int Dwc_Svlprocess(void);
undefined4 Dwc_NasloginAsync(void);
undefined4 Dwc_NasloginProcess(void);
void Dwci_NdAlloc(int param_1, undefined4 param_2);
void Dwci_NdFree(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_NdCallback(undefined4 param_1, int param_2, int param_3);
void Dwci_NdCleanupCallback(void);
void Dwci_SvltokenWaitThread(void);
undefined4 Dwc_NdInitAsync(undefined4 param_1, char* param_2, char* param_3);
undefined4 Dwc_NdCleanupAsync(undefined4 param_1);
undefined4 Dwc_NdSetAttr(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined4 Dwc_NdGetFileListNumAsync(undefined4 param_1);
undefined4 Dwc_NdGetFileListAsync(int8_t* param_1, undefined4 param_2, int param_3);
undefined4 Dwc_NdGetFileAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined4 Dwc_NdGetProgress(undefined4 param_1, undefined4 param_2);
void Aoss_Malloc(void);
void Aoss_Free(void);
undefined4 Aossi_Init(int param_1);
void Aoss_Release(void);
void Aoss_Data_Init(uint16_t* param_1);
undefined4 Aoss_Seq_Data_Copy(uint16_t* param_1);
undefined4 Aoss_Check_Str(int8_t* param_1, int param_2);
undefined4 Aoss_CheckAp(unsigned int *param_1);
undefined4 Aoss_Set_ApInfo(undefined4* param_1);
void MakeSendSeqID(int param_1, int param_2, undefined4 param_3);
undefined4 Aoss_StatusExclusion(int param_1);
undefined4 RecvMessage(undefined4 param_1, int param_2, int* param_3, undefined4 param_4);
int AstsSetInitRes(int param_1, int param_2, int* param_3, undefined4 param_4);
int AstsSetSecureRes(int param_1, int param_2, int* param_3, int param_4);
int AstsRestartRes(int param_1, int param_2, int* param_3, int param_4);
int DecodePacket(int param_1);
undefined4 CheckSeqID(int param_1, undefined4 param_2);
undefined4 CheckRecvSeqID(int param_1, int param_2);
undefined4 GetProductInfo(undefined1* param_1, int param_2, undefined4 param_3, undefined4 param_4);
int Aoss_Get_Bin(int param_1, int param_2);
undefined4 GetWepData(int param_1, int param_2);
undefined4 GetWpaData(int param_1, int param_2);
undefined4 GetBssidData(int param_1, undefined4 param_2);
int GetSecurityData(int param_1, char* param_2, int param_3, int param_4, int param_5);
bool GetSecurityType(unsigned int param_1);
undefined4 SendMessage(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
undefined4 AstsSetInitReq(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                          undefined4 param_4);
undefined4 AstsSetSecureReq(undefined4 param_1, int param_2, undefined4 param_3,
                            undefined4 param_4);
undefined4 AstsRestartReq(undefined4 param_1, int param_2, undefined4 param_3, undefined4 param_4);
int SetStaData(undefined1* param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void PacketDataSet(int param_1, undefined2* param_2, undefined4 param_3, int16_t* param_4,
                   undefined2* param_5, undefined4 param_6);
void SetPacketHeader(undefined2* param_1, undefined2 param_2, undefined2 param_3,
                     undefined2 param_4, undefined1 param_5, undefined1 param_6,
                     undefined4 param_7);
void SendPacketUdp(undefined4 param_1, undefined4 param_2, int param_3, undefined4 param_4);
undefined4 EncodeRC4(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                     undefined1* param_4, undefined4 param_5, undefined4 param_6, int param_7);
undefined4 DecodeRC4(undefined4 param_1, undefined4 param_2, undefined4 param_3, int param_4,
                     undefined4 param_5, undefined4 param_6, int param_7);
void RC4encrypt(undefined4 param_1, int param_2, int param_3, unsigned int param_4);
int8_t Crc(undefined4 param_1, undefined4 param_2);
unsigned int Update_Crc(unsigned int param_1, int param_2, int param_3, int param_4, int param_5);
void Make_Crc_Table(undefined4 param_1, unsigned int* param_2);
undefined4 CryptSeqNo(undefined4 param_1, int param_2, undefined4 param_3, undefined4 param_4);
void AddKey(int param_1, int param_2, int param_3);
void Rotate(int param_1, int param_2, int param_3, undefined4 param_4);
int Aoss_Memcmp(int8_t* param_1, int8_t* param_2, int param_3);
void Aoss_Memcpy(undefined4* param_1, undefined4* param_2, unsigned int param_3);
void Aoss_Memset(int8_t* param_1, unsigned int param_2, unsigned int param_3);
void ret_0213e00c(void);
int SocketVeneer(int __domain, int __type, int __protocol);
int CloseVeneer(int __fd);
unsigned int Aoss_Htonl(unsigned int param_1);
unsigned int Aoss_Htons(unsigned int param_1);
unsigned int Aoss_Ntohl(unsigned int param_1);
unsigned int Aoss_Ntohs(unsigned int param_1);
int Aoss_Strlen(char* param_1);
undefined4 Aossi_InitLocal(void* *param_1,void* *param_2,undefined4 param_3,undefined4 param_4);
void OS_SleepVeneer(void);
undefined4 Aossi_Status(void);
uint16_t* GetFrameData(uint16_t* param_1, unsigned int* param_2, unsigned int* param_3);
uint16_t* GetElementData(int* param_1, uint16_t* param_2, unsigned int* param_3,
                         unsigned int* param_4);
void GetFirstElement(uint16_t* param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void SetSingleElement(int16_t* param_1);
undefined4 IsSearchCommand(undefined4 param_1, unsigned int* param_2);
void SetSearchRes(undefined4 param_1);
undefined4 AsciiToHex(int param_1, int param_2, int param_3);
void Aeskw_Xor64(int8_t* param_1, int8_t* param_2, int8_t* param_3);
undefined4 RijndaelKeySetupEnc(unsigned int* param_1, int8_t* param_2, int param_3);
int RijndaelKeySetupDec(unsigned int* param_1);
void RijndaelEncrypt(unsigned int* param_1, int param_2, int8_t* param_3, undefined1* param_4);
void RijndaelDecrypt(unsigned int* param_1, int param_2, int8_t* param_3, undefined1* param_4);
void MY_MD5Init(undefined4* param_1);
void MY_MD5Update(int param_1, int param_2, unsigned int param_3, undefined4 param_4);
void MY_MD5Final(undefined4 param_1, int param_2, undefined4 param_3, undefined4 param_4);
void MD5Transform(int* param_1, undefined4 param_2);
void Encode(int param_1, undefined4* param_2, unsigned int param_3);
void Decode(undefined4* param_1, int param_2, unsigned int param_3);
void MD5_Memcpy(int param_1, int param_2, unsigned int param_3);
void MD5_Memset(undefined1* param_1, undefined1 param_2, unsigned int param_3);
void MD5Encode(undefined4 param_1, undefined4 param_2, undefined4 param_3);
int PutHex(char* param_1, unsigned int param_2);
int PutMac(undefined1* param_1, char* param_2);
int Atermi_ApConfigStart(undefined4 param_1,undefined4 param_2,undefined4 param_3,void* *param_4,undefined4 param_5,unsigned int param_6);
undefined4 ATERMi_ApConfigEnd(void);
undefined4 Atermi_ApConfigGetState(undefined4* param_1);
undefined4 ATERMi_ApConfigGetResult(void *param_1);
void SendNotify(void);
void Dwci_AnimelInitEx(int param_1);
void Dwci_AnimelEnd(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Anime_TaskAnime(void);
void Dwci_BtnlInit(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_BtnlEnd(void);
int Dwci_BtnlGet(void);
void Dwci_BtnlSet(undefined1 param_1);
void Dwci_BtnlSetForce(undefined1 param_1);
bool Dwci_BtnlIsEnd(void);
void Dwci_BtnlEnable(void);
void Dwci_BtnlDisable(void);
void Button_Disp(int param_1);
void Button_TaskStart(undefined4 param_1);
void Button_TaskStart1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Button_TaskMain(void);
void Button_TaskEnd(undefined4 param_1);
void Button_TaskEnd1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Button_TaskRelease(undefined4 param_1);
void Dwci_CommentlInit(void);
undefined4 Dwci_CommentlDispEx(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined4 Dwci_CommentlDelete(void);
void Dwci_Char(char* param_1);
void Dwci_CmnlLoadResource(undefined4 param_1, void** param_2, undefined4 param_3,
                           undefined4 param_4);
void Dwci_CmnlStep(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_CmnlButton(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                     undefined4 param_4);
void Dwci_CmnlMsgDraw(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                      undefined4 param_4);
void Dwci_CmnlMsgNameDraw(undefined4 param_1, undefined4 param_2);
undefined4 Dwci_CmnlFontFlag(void);
void Dwci_FocuslInit(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                     undefined4 param_4);
void Dwci_FocuslEnd(void);
void Dwci_FocuslDisp(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_FocuslDisp4(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                      undefined4 param_4);
void Dwci_FocuslDelete(void);
void Dwci_HLlInit(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void DWCi_HLlEnd(void);
void Dwci_HLlLoad(int param_1);
void Dwci_HLlLoadSet(void);
void Dwci_HLlLoadList(void);
void Headline_TaskLoad(undefined4 param_1);
void Dwci_IconlInit(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_IconlEnd(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Icon_TaskRenew(void);
void Dwci_KBlInit(void);
void Dwci_KBlEnd(void);
undefined1 Dwci_KBlGet(void);
void Dwci_KBlSetErase(undefined1 param_1);
void Dwci_KBlSetInput(undefined1 param_1);
bool Dwci_KBlIsInit(void);
void Keyboard_TaskStart0(undefined4 param_1);
void Keyboard_TaskStart1(undefined4 param_1);
void Keyboard_TaskStart2(undefined4 param_1);
void Keyboard_TaskStart3(undefined4 param_1);
void Keyboard_TaskStart4(undefined4 param_1);
void Keyboard_TaskMain(void);
void Keyboard_TouchTriger(void);
void Keyboard_TouchRelease(void);
void Keyboard_PushCaps(void);
void Keyboard_PushShift(void);
void Keyboard_Touch(void);
void Keyboard_ExchangeBack(int param_1);
void Keyboard_Key(void);
void Keyboard_Disp(int param_1,int param_2,unsigned int param_3,undefined4 param_4);
void Keyboard_ChangePage(int param_1);
void Keyboard_ChangeColor(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
void Keyboard_DispFocus(void);
void Keyboard_MoveFocus(int param_1);
void Keyboard_TaskEnd0(undefined4 param_1);
void Keyboard_TaskEnd1(undefined4 param_1);
void Keyboard_TaskEnd2(undefined4 param_1);
void Keyboard_TaskEnd3(undefined4 param_1);
void Keyboard_TaskEnd4(undefined4 param_1);
void Keyboard_TaskEnd5(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_KB10lInit(void);
void Dwci_KB10lEnd(void);
undefined1 Dwci_KB10lGet(void);
void Dwci_KB10lSetErase(undefined1 param_1);
void Dwci_KB10lSetInput(undefined1 param_1);
void Dwci_KB10lSetShift(undefined1 param_1);
bool Dwci_KB10lIsInit(void);
void Keyboard10_TaskStart0(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Keyboard10_TaskStart1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Keyboard10_TaskStart2(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Keyboard10_TaskStart3(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Keyboard10_TaskStart4(undefined4 param_1);
void Keyboard10_TaskMain(void);
void Keyboard10_TouchTriger(void);
void Keyboard10_TouchRelease(void);
void Keyboard10_Touch(void);
void Keyboard10_ExchangeBack(int param_1);
void Keyboard10_Key(void);
void Keyboard10_Disp(int param_1,unsigned int param_2);
void Keyboard10_ChangeColor(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
void Keyboard10_DispFocus(void);
void Keyboard10_MoveFocus(int param_1);
void Keyboard10_TaskEnd0(undefined4 param_1);
void Keyboard10_TaskEnd1(undefined4 param_1);
void Keyboard10_TaskEnd2(undefined4 param_1);
void Keyboard10_TaskEnd3(undefined4 param_1);
void Keyboard10_TaskEnd4(undefined4 param_1);
void Keyboard10_TaskEnd5(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_AosslInit(void);
void DWCi_AOSSlEnd(int param_1);
undefined4 DWCi_AOSSlStart(void);
void LibAoss_AossAlloc(undefined4 param_1);
void LibAoss_AossFree(void *param_1);
undefined4 Dwc_StartUtility(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                            undefined4 param_4);
undefined4 Main_CheckParam(int param_1,unsigned int param_2);
void Main_InitGame(void);
void Main_InitGraph(void);
void Main_ProcEnd(void);
void DWCi_ChangeScene(undefined4 param_1);
void Dwci_SetParam(undefined4 param_1, undefined4 param_2);
void Dwci_GetParam(undefined4* param_1, undefined4* param_2);
void Dwci_SetParam2(undefined4 param_1, undefined4 param_2);
void Dwci_GetParam2(undefined4* param_1, undefined4* param_2);
undefined1 DWCi_Language(void);
unsigned int Dwci_Entry(void);
bool Dwci_Flag(unsigned int param_1);
void Dwci_EndUtility(void);
char KDwci_Language(void);
void Dwci_MsglInit(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void DWCi_MSGlEnd(void);
int* Dwci_MsglRead(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_MsglRelease(int param_1);
int Dwci_MsglGet(int* param_1, unsigned int param_2);
void Dwci_MsglGetEx(int* param_1, unsigned int param_2, int param_3, int16_t param_4);
void Dwci_MovlInit(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_MovlEnd(void);
void Move_TaskEnd(undefined4 param_1);
bool Dwci_MovlIsEnd(void);
void Dwci_MovlChangeCallback(undefined4 param_1);
void Dwci_MovStartDownloadandBootChild(void);
int Dwci_MovlGetChild(void);
void Move_TaskFramework(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DWCi_RakulInit(void);
void DWCi_RAKUlEnd(void);
undefined4 DWCi_RAKUlGetState(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DWCi_RAKUlSetResult(void);
void Rakuraku_CbConfig(undefined4 *param_1);
void Rakuraku_MemAlloc(undefined4 param_1);
void RakuRaku_MemFree(void *param_1);
void Dwci_SceneEnd(void);
void SceneEnd_EndScene(void);
void Dwci_SceneInit(void);
void SceneInit_ProcFade(void);
void SceneInit_ProcWait(void);
void Dwci_SceneMenu(void);
void SceneMenu_InitGraphics(void);
void SceneMenu_ProcInit(void);
void SceneMenu_ProcInit1(void);
void SceneMenu_ProcInit2(void);
void SceneMenu_ProcScene(void);
void SceneMenu_Input(void);
void SceneMenu_Draw(void);
void SceneMenu_Button(void);
void SceneMenu_EndScene(void);
void SceneMenu_EndScene1(void);
void SceneMenu_EndScene2(void);
void SceneMenu_MoveFocus(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneMenu_DispPushButton(void);
void Dwci_SceneOptErase(void);
void SceneOptErase_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneOptErase_ProcInit(void);
void SceneOptErase_ProcInit1(void);
void SceneOptErase_ProcInit2(void);
void SceneOptErase_ProcScene(void);
void SceneOptErase_Input(void);
void SceneOptErase_Draw(void);
void SceneOptErase_Button(void);
void SceneOptErase_EndScene(void);
void SceneOptErase_EndScene1(void);
void SceneOptErase_EndScene2(void);
void SceneOptErase_ProcConfirm(void);
void SceneOptErase_ProcConfirm1(void);
void DWCi_SceneOptErase1(void);
void SceneOptErase1_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneOptErase1_ProcInit(void);
void SceneOptErase1_ProcInit1(void);
void SceneOptErase1_ProcInit2(void);
void SceneOptErase1_ProcScene(void);
void SceneOptErase1_Input(void);
void SceneOptErase1_Draw(void);
void SceneOptErase1_Button(void);
void SceneOptErase1_EndScene(void);
void SceneOptErase1_EndScene1(void);
void SceneOptErase1_EndScene2(void);
void Dwci_SceneOptInfo(void);
void SceneOptInfo_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneOptInfo_DrawInfo(void);
void SceneOptInfo_ProcInit(void);
void SceneOptInfo_ProcInit1(void);
void SceneOptInfo_ProcInit2(void);
void SceneOptInfo_ProcScene(void);
void SceneOptInfo_Input(void);
void SceneOptInfo_Draw(void);
void SceneOptInfo_Button(void);
void SceneOptInfo_EndScene(void);
void SceneOptInfo_EndScene1(void);
void SceneOptInfo_EndScene2(void);
void Dwci_SceneOptMenu(void);
void SceneOptMenu_InitGraphics(void);
void SceneOptMenu_ProcInit(void);
void SceneOptMenu_ProcInit1(void);
void SceneOptMenu_ProcInit2(void);
void SceneOptMenu_ProcScene(void);
void SceneOptMenu_Input(void);
void SceneOptMenu_Draw(void);
void SceneOptMenu_Button(void);
void SceneOptMenu_EndScene(void);
void SceneOptMenu_EndScene1(void);
void SceneOptMenu_EndScene2(void);
void SceneOptMenu_MoveFocus(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneOptMenu_DispPush(void);
void Dwci_SceneOptMovComm(void);
void SceneOptMovComm_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneOptMovComm_ProcInit(void);
void SceneOptMovComm_ProcInit1(void);
void SceneOptMovComm_ProcScene(void);
void SceneOptMovComm_Input(void);
void SceneOptMovComm_Draw(void);
void SceneOptMovComm_EndScene(void);
void SceneOptMovComm_EndScene1(void);
void SceneOptMovComm_CbMov(int param_1);
void SceneOptMovComplete_InitGraphics(void);
void SceneOptMovComplete_ProcInit(void);
void SceneOptMovComplete_ProcInit1(void);
void SceneOptMovComplete_ProcInit2(void);
void SceneOptMovComplete_ProcScene(void);
void SceneOptMovComplete_Input(void);
void SceneOptMovComplete_Draw(void);
void SceneOptMovComplete_Button(void);
void SceneOptMovComplete_EndScene(void);
void SceneOptMovComplete_EndScene1(void);
void SceneOptMovComplete_EndScene2(void);
void DWCi_SceneOptMovConfirm(void);
void SceneOptMovConfirm_InitGraphics(void);
void SceneOptMovConfirm_ProcInit(void);
void SceneOptMovConfirm_ProcInit1(void);
void SceneOptMovConfirm_ProcInit2(void);
void SceneOptMovConfirm_ProcScene(void);
void SceneOptMovConfirm_Input(void);
void SceneOptMovConfirm_Draw(void);
void SceneOptMovConfirm_Button(void);
void SceneOptMovConfirm_EndScene(void);
void SceneOptMovConfirm_EndScene1(void);
void SceneOptMovConfirm_EndScene2(void);
void Dwci_SceneOptMovConfirm1(void);
void SceneOptMovConfirm1_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneOptMovConfirm1_ProcInit(void);
void SceneOptMovConfirm1_ProcInit1(void);
void SceneOptMovConfirm1_ProcInit2(void);
void SceneOptMovConfirm1_ProcScene(void);
void SceneOptMovConfirm1_Input(void);
void SceneOptMovConfirm1_Draw(void);
void SceneOptMovConfirm1_Button(void);
void SceneOptMovConfirm1_EndScene(void);
void SceneOptMovConfirm1_EndScene1(void);
void SceneOptMovConfirm1_EndScene2(void);
void Dwci_SceneOptMovDisconnect(void);
void SceneOptMovDisconnect_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneOptMovDisconnect_ProcInit(void);
void SceneOptMovDisconnect_ProcInit1(void);
void SceneOptMovDisconnect_ProcScene(void);
void SceneOptMovDisconnect_Draw(void);
void SceneOptMovDisconnect_EndScene(void);
void SceneOptMovDisconnect_EndScene1(void);
void SceneOptMovDisconnect_Wait(void);
void Dwci_SceneOptMovFailure(void);
void SceneOptMovFailure_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneOptMovFailure_ProcInit(void);
void SceneOptMovFailure_ProcInit1(void);
void SceneOptMovFailure_ProcInit2(void);
void SceneOptMovFailure_ProcScene(void);
void SceneOptMovFailure_Input(void);
void SceneOptMovFailure_Draw(void);
void SceneOptMovFailure_Button(void);
void SceneOptMovFailure_EndScene(void);
void SceneOptMovFailure_EndScene1(void);
void SceneOptMovFailure_EndScene2(void);
void Dwci_SceneOptMovUser(void);
void SceneOptMovUser_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneOptMovUser_ProcInit(void);
void SceneOptMovUser_ProcInit1(void);
void SceneOptMovUser_ProcInit2(void);
void SceneOptMovUser_procScene(void);
void SceneOptMovUser_Input(void);
void SceneOptMovUser_Draw(void);
void SceneOptMovUser_EndScene(void);
void SceneOptMovUser_EndScene1(void);
void SceneOptMovUser_EndScene2(void);
void SceneOptMovUser_ObMov(void);
bool DWCi_IsFold_SceneOptMovWait(void);
void Dwci_SceneOptMovWait(void);
void SceneOptMovWait_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneOptMovWait_ProcInit(void);
void SceneOptMovWait_ProcInit1(void);
void SceneOptMovWait_ProcInit2(void);
void SceneOptMovWait_ProcScene(void);
void SceneOptMovWait_Input(void);
void SceneOptMovWait_Draw(void);
void SceneOptMovWait_Button(void);
void SceneOptMovWait_EndScene(void);
void SceneOptMovWait_EndScene1(void);
void SceneOptMovWait_EndScene2(void);
void SceneOptMovWait_CbMov(int param_1);
bool DWCi_IsFold_SceneSetAossButton(void);
void Dwci_SceneSetAossButton(void);
void SceneSetAossButton_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetAossButton_ProcInit(void);
void SceneSetAossButton_ProcInit1(void);
void SceneSetAossButton_ProcInit2(void);
void SceneSetAossButton_ProcScene(void);
void SceneSetAossButton_Input(void);
void SceneSetAossButton_Draw(void);
void SceneSetAossButton_Button(void);
void SceneSetAossButton_EndScene(void);
void SceneSetAossButton_EndScene1(void);
void SceneSetAossButton_EndScene2(void);
void SceneSetAossButton_TaskVBlank(void);
void SceneSetAossButton_ProcError(void);
void SceneSetAossButton_ProcError1(void);
void SceneSetAossButton_ProcWait(void);
void SceneSetAossButton_ProcCancel(void);
void Dwci_SceneSetAossComplete(void);
void SceneSetAossComplete_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetAossComplete_ProcInit(void);
void SceneSetAossComplete_ProcInit1(void);
void SceneSetAossComplete_ProcScene(void);
void SceneSetAossComplete_Draw(void);
void SceneSetAossComplete_EndScene(void);
void SceneSetAossComplete_EndScene1(void);
void SceneSetAossComplete_Wait(void);
void Dwci_SceneSetApList(void);
void SceneSetApList_InitGraphics(void);
void SceneSetApList_InitScrollBar(void);
void SceneSetApList_GetCharName(void);
void SceneSetApList_ProcInit(void);
void SceneSetApList_ProcInit1(void);
void SceneSetApList_ProcInit2(void);
void SceneSetApList_ProcScene(void);
void SceneSetApList_Input(void);
void SceneSetApList_Draw(void);
void SceneSetApList_Button(void);
void SceneSetApList_EndScene(void);
void SceneSetApList_EndScene1(void);
void SceneSetApList_EndScene2(void);
void SceneSetApList_DrawApInfo(void);
void SceneSetApList_DrawAp(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
void SceneSetApList_DrapApObj(int param_1,int param_2);
void SceneSetApList_SetOffset(void);
void SceneSetApList_TaskUp(undefined4 param_1);
void SceneSetApList_TaskDown(undefined4 param_1);
void SceneSetApList_TaskVBlank(void);
void SceneSetApList_DispFocus(void);
void SceneSetApList_MoveFocus(int param_1);
void SceneSetApList_ScrollUp(void);
void SceneSetApList_ScrollDown(void);
void SceneSetApList_DispPushButton(void);
void SceneSetApList_procError(void);
void SceneSetApList_procError1(void);
void Dwci_SceneSetEdit32(void);
void SceneSetEdit32_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetEdit32_ProcInit(void);
void SceneSetEdit32_ProcInit1(void);
void SceneSetEdit32_ProcInit2(void);
void SceneSetEdit32_ProcScene(void);
void SceneSetEdit32_Input(void);
void SceneSetEdit32_Draw(void);
void SceneSetEdit32_EndScene(void);
void SceneSetEdit32_EndScene1(void);
void SceneSetEdit32_EndScene2(void);
void SceneSetEdit32_EndScene3(void);
void SceneSetEdit32_DrawSsid(void);
void SceneSetEdit32_DispCaret(void);
void SceneSetEdit32_ProcWin(void);
void SceneSetEdit32_ProcWin1(void);
bool SceneSetEdit32_IsCorrect(void);
void SceneSetEdit32_ProcError(void);
void SceneSetEdit32_ProcError1(void);
void Dwci_SceneSetEditAddress(void);
void SceneSetEditAddress_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetEditAddress_ProcInit(void);
void SceneSetEditAddress_ProcInit1(void);
void SceneSetEditAddress_ProcInit2(void);
void SceneSetEditAddress_ProcScene(void);
void SceneSetEditAddress_Input(void);
bool SceneSetEditAddress_IsOver(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetEditAddress_Draw(void);
void SceneSetEditAddress_EndScene(void);
void SceneSetEditAddress_EndScene1(void);
void SceneSetEditAddress_EndScene2(void);
void SceneSetEditAddress_EndScene3(void);
void SceneSetEditAddress_DrawAddress(void);
void SceneSetEditAddress_DispCaret(void);
void SceneSetEditAddress_ProcWin(void);
void SceneSetEditAddress_ProcWin1(void);
void SceneSetEditAddress_ArrangeAddress(void);
bool SceneSetEditAddress_IsCorrect(void);
void SceneSetEditAddress_ProcError(void);
void SceneSetEditAddress_procError1(void);
void DWCi_SceneSetError(void);
void SceneSetError_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetError_DrawMessage(void);
void SceneSetError_ProcInit(void);
void SceneSetError_ProcInit1(void);
void SceneSetError_ProcInit2(void);
void SceneSetError_ProcScene(void);
void SceneSetError_Input(void);
void SceneSetError_Draw(void);
void SceneSetError_Button(void);
void SceneSetError_EndScene(void);
void SceneSetError_EndScene1(void);
void SceneSetError_EndScene2(void);
void DWCi_SetErrorCode(undefined4 param_1);
void Dwci_SceneSetList(void);
void SceneSetList_InitGraphics(void);
void SceneSetList_CalcParam(void);
void SceneSetList_ProcInit(void);
void SceneSetList_ProcInit1(void);
void SceneSetList_ProcScene(void);
void SceneSetList_Input(void);
undefined4 SceneSetList_InputWinButton(void);
void SceneSetList_PushWinButton(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetList_PushIpAuto(unsigned int param_1);
void SceneSetList_PushDnsAuto(unsigned int param_1);
void SceneSetList_Draw(void);
void SceneSetList_EndScene(void);
void SceneSetList_EndScene1(void);
void SceneSetList_EndScene2(void);
void SceneSetList_DrawWindow(void);
void SceneSetList_DrawColumnChar(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetList_DrawColumnObj(undefined4 param_1,undefined4 param_2);
bool SceneSetList_IsEnablePush(undefined4 param_1);
void SceneSetList_DispObj(int param_1,int param_2,int param_3,undefined4 param_4);
void SceneSetList_DrawString(int param_1,int param_2);
void SceneSetList_DrawAddress(undefined1 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void SceneSetList_SetOffset(void);
unsigned int SceneSetList_IsPush(void);
int SceneSetList_CalcColumnIdx(int param_1);
int SceneSetList_CalcIdxColumn(int param_1);
void SceneSetList_TaskUp(undefined4 param_1);
void SceneSetList_TaskDown(undefined4 param_1);
void SceneSetList_TaskVBlank(void);
void SceneSetList_DispFocus(void);
void SceneSetList_ApplyForcus(void);
void SceneSetList_ApplyForcus1(int param_1);
void SceneSetList_MoveFocus(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetList_DispPushButton(void);
void SceneSetList_TaskPushCount(void);
void SceneSetList_PushButtonYesNo(void);
undefined4 SceneSetList_IsCorrect(void);
void SceneSetList_ProcError(void);
void SceneSetList_ProcError1(void);
void DWCi_SetListReturn(undefined1 param_1);
void DWCi_SceneSetListSave(void);
void SceneSetListSave_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetListSave_ProcInit(void);
void SceneSetListSave_ProcInit1(void);
void SceneSetListSave_ProcScene(void);
void SceneSetListSave_Input(void);
void SceneSetListSave_Draw(void);
void SceneSetListSave_EndScene(void);
void SceneSetListSave_EndScene1(void);
bool DWCi_IsFold_SceneSetRakuButton(void);
void DWCi_SceneSetRakuButton(void);
void SceneSetRakuButton_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetRakuButton_ProcInit(void);
void SceneSetRakuButton_ProcInit1(void);
void SceneSetRakuButton_ProcInit2(void);
void SceneSetRakuButton_ProcScene(void);
void SceneSetRakuButton_Input(void);
void SceneSetRakuButton_Draw(void);
void SceneSetRakuButton_Button(void);
void SceneSetRakuButton_EndScene(void);
void SceneSetRakuButton_EndScene1(void);
void SceneSetRakuButton_EndScene2(void);
void SceneSetRakuButton_CheckRaku(void);
void SceneSetRakuButton_ProcError(void);
void SceneSetRakuButton_ProcError1(void);
bool DWCi_IsFold_SceneSetRakuButton1(void);
void SceneSetRakuButton1_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetRakuButton1_ProcInit(void);
void SceneSetRakuButton1_ProcInit1(void);
void SceneSetRakuButton1_ProcInit2(void);
void SceneSetRakuButton1_ProcScene(void);
void SceneSetRakuButton1_Input(void);
void SceneSetRakuButton1_Draw(void);
void SceneSetRakuButton1_Button(void);
void SceneSetRakuButton1_EndScene(void);
void SceneSetRakuButton1_EndScene1(void);
void SceneSetRakuButton1_EndScene2(void);
void SceneSetRakuButton1_CheckRaku(void);
void SceneSetRakuButton1_ProcError(void);
void SceneSetRakuButton1_ProcError1(void);
void Dwci_SceneSetRakuComplete(void);
void SceneSetRakuComplete_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetRakuComplete_ProcInit(void);
void SceneSetRakuComplete_ProcInit1(void);
void SceneSetRakuComplete_ProcScene(void);
void SceneSetRakuComplete_Draw(void);
void SceneSetRakuComplete_EndScene(void);
void SceneSetRakuComplete_EndScene1(void);
void SceneSetRakuComplete_Wait(void);
bool DWCi_IsFold_SceneSetRakuReady(void);
void Dwci_SceneSetRakuReady(void);
void SceneSetRakuReady_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetRakuReady_ProcInit(void);
void SceneSetRakuReady_ProcInit1(void);
void SceneSetRakuReady_ProcInit2(void);
void SceneSetRakuReady_ProcScene(void);
void SceneSetRakuReady_Input(void);
void SceneSetRakuReady_Draw(void);
void SceneSetRakuReady_Button(void);
void SceneSetRakuReady_EndScene(void);
void SceneSetRakuReady_EndScene1(void);
void SceneSetRakuReady_EndScene2(void);
void SceneSetRakuReady_CheckRaku(void);
void SceneSetRakuReady_ProcError(void);
void SceneSetRakuReady_ProcError1(void);
void Dwci_SceneSetSearch(void);
void SceneSetSearch_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetSearch_ProcInit(void);
void SceneSetSearch_ProcInit1(void);
void SceneSetSearch_ProcInit2(void);
void SceneSetSearch_ProcScene(void);
void SceneSetSearch_IsEnd(void);
void SceneSetSearch_Input(void);
void SceneSetSearch_Draw(void);
void SceneSetSearch_Button(void);
void SceneSetSearch_EndScene(void);
void SceneSetSearch_EndScene1(void);
void SceneSetSearch_EndScene2(void);
void SceneSetSearch_ProcError(void);
void SceneSetSearch_ProcError1(void);
void Dwci_SceneSetSelectAp(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                           undefined4 param_4);
void SceneSetSelectAp_InitGraphics(void);
void SceneSetSelectAp_InitObj(void);
void SceneSetSelectAp_ProcInit(void);
void SceneSetSelectAp_ProcInit1(void);
void SceneSetSelectAp_ProcInit2(void);
void SceneSetSelectAp_ProcScene(void);
void SceneSetSelectAp_Input(void);
void SceneSetSelectAp_Draw(void);
void SceneSetSelectAp_Button(void);
void SceneSetSelectAp_EndScene(void);
void SceneSetSelectAp_EndScene1(void);
void SceneSetSelectAp_EndScene2(void);
void SceneSetSelectAp_DispFocus(void);
void SceneSetSelectAp_MoveFocus(int param_1);
void SceneSetSelectAp_DispPushClear(void);
void SceneSetSelectAp_ProcErase(void);
void SceneSetSelectAp_ProcErase1(void);
void SceneSetSelectAp_DispPush(void);
void Dwci_SceneSetSelectWay(void);
void SceneSetSelectWay_InitGraphics(void);
void SceneSetSelectWay_ProcInit(void);
void SceneSetSelectWay_ProcInit1(void);
void SceneSetSelectWay_ProcInit2(void);
void SceneSetSelectWay_ProcScene(void);
void SceneSetSelectWay_Input(void);
void SceneSetSelectWay_Draw(void);
void SceneSetSelectWay_Button(void);
void SceneSetSelectWay_EndScene(void);
void SceneSetSelectWay_EndScene1(void);
void SceneSetSelectWay_EndScene2(void);
void SceneSetSelectWay_MoveFocus(int param_1);
void SceneSetSelectWay_DispPush(void);
void Dwci_SceneSetTest(void);
void SceneSetTest_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetTest_InitAc(void);
void SceneSetTest_ProcInit(void);
void SceneSetTest_ProcInit1(void);
void SceneSetTest_ProcScene(void);
void ret_02153660(void);
void ret_02153664(void);
void ret_02153668(void);
void SceneSetTest_EndScene(void);
void SceneSetTest_EndScene1(void);
void SceneSetTest_EndScene2(void);
void SceneSetTest_TaskAc(undefined4 param_1);
int8_t * SceneSetTest_AcAlloc(undefined4 param_1,unsigned int param_2);
void SceneSetTest_AcFree(undefined4 param_1,int param_2);
void DWCi_SceneSetTestComplete(void);
void SceneSetTestComplete_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetTestComplete_ProcInit(void);
void SceneSetTestComplete_ProcInit2(void);
void SceneSetTestComplete_ProcScene(void *param_1);
void SceneSetTestComplete_Draw(void);
void SceneSetTestComplete_EndScene(void);
void SceneSetTestComplete_EndScene1(void);
void SceneSetTestComplete_Wait(void *__stat_loc);
void Dwci_SceneSetTestConfirm(void);
void SceneSetTestConfirm_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetTestConfirm_ProcInit(void);
void SceneSetTestConfirm_ProcInit1(void);
void SceneSetTestConfirm_ProcScene(void);
void SceneSetTestConfirm_Input(void);
void SceneSetTestConfirm_Draw(void);
void SceneSetTestConfirm_EndScene(void);
void SceneSetTestConfirm_EndScene1(void);
void Dwci_SceneSetUsbComplete(void);
void SceneSetUsbComplete_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetUsbComplete_ProcInit(void);
void SceneSetUsbComplete_ProcInit1(void);
void SceneSetUsbComplete_ProcScene(void);
void SceneSetUsbComplete_Draw(void);
void SceneSetUsbComplete_EndScene(void);
void SceneSetUsbComplete_EndScene1(void);
void SceneSetUsbComplete_Wait(void);
void DWCi_SceneSetUsbReady(void);
void SceneSetUsbReady_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetUsbReady_ProcInit(void);
void SceneSetUsbReady_ProcInit1(void);
void SceneSetUsbReady_ProcInit2(void);
void SceneSetUsbReady_ProcScene(void);
void SceneSetUsbReady_Input(void);
void SceneSetUsbReady_Draw(void);
void SceneSetUsbReady_Button(void);
void SceneSetUsbReady_EndScene(void);
void SceneSetUsbReady_EndScene1(void);
void SceneSetUsbReady_EndScene2(void);
bool DWCi_IsFold_SceneSetUsbReady1(void);
void Dwci_SceneSetUsbReady1(void);
void SceneSetUsbReady1_InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SceneSetUsbReady1_ProcInit(void);
void SceneSetUsbReady1_ProcInit1(void);
void SceneSetUsbReady1_ProcInit2(void);
void SceneSetUsbReady1_ProcScene(void);
void SceneSetUsbReady1_Input(void);
void SceneSetUsbReady1_Draw(void);
void SceneSetUsbReady1_Button(void);
void SceneSetUsbReady1_EndScene(void);
void SceneSetUsbReady1_EndScene1(void);
void SceneSetUsbReady1_EndScene2(void);
void SceneSetUsbReady1_CbUsb(undefined4 param_1);
void SceneSetUsbReady1_ProcNotFound(void);
void SceneSetUsbReady1_ProcNotFound1(void);
void SceneSetUsbReady1_ProcBoth(void);
void SceneSetUsbReady1_ProcBoth1(void);
void Dwci_ScreenlInit(undefined4 param_1);
void Dwci_ScreenlEnd(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                     undefined4 param_4);
void Dwci_ScreenlRenew(void);
void Dwci_ScreenlCopy(int param_1, int param_2, int param_3, int param_4);
void Screen_TaskLoad(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_ScreenlCopyPalette(int param_1, int param_2, int param_3, undefined4 param_4);
void Screen_TaskCopyPltt(undefined4 param_1);
void Dwci_ScreenlSetPalette(undefined4 param_1);
void Screen_TaskSetPltt(undefined4 param_1);
void Dwci_SBlInit(int param_1, undefined1 param_2, undefined4 param_3, int param_4, int param_5);
void Dwci_SBlEnd(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
undefined1 Dwci_SBlGet(void);
undefined1 Dwci_SBlGetState(void);
void DWCi_SBlSet(int param_1);
void Dwci_SBlEnable(void);
void Dwci_SBlDisable(void);
void ScrollBar_TaskMain(void);
void ScrollBar_MoveBar(void);
void ScrollBar_PlaySound(int param_1);
void ScrollBar_StepBar(int param_1);
void ScrollBar_SetBar(void);
int ScrollBar_IsTrigger(void);
int ScrollBar_IsTouch(void);
void ScrollBar_CalcRect(undefined4 param_1,int16_t *param_2);
void ScrollBar_Disp(int param_1);
void Dwci_SearchlInit(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                      undefined4 param_4);
void Dwci_SearchlEnd(void);
bool Dwci_SearchlBegin(void);
bool Search_StartScan(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
bool Dwci_SearchlStop(void);
int Dwci_SearchlGetApInfo(int* param_1);
void Search_Callback(uint16_t *param_1);
void Search_RenewInfo(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SettignlInit(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                       undefined4 param_4);
void DWCi_SETTIGNlEnd(void);
int Dwci_SettignlGet(void);
void DWCi_SETTINGlSetIpAuto(undefined1 param_1);
void Dwci_SettinglSetDnsAuto(undefined1 param_1);
void Dwci_SettinglSetSsid(undefined4* param_1);
void Dwci_SettinglSetWep(undefined4* param_1);
void DWCi_SETTINGlSetIp(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DWCi_SETTINGlSetNetMask(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DWCi_SETTINGlSetGateway(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DWCi_SETTINGlSetDnsP(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DWCi_SETTINGlSetDnsS(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SettinglGetSsid(undefined4* param_1);
void DWCi_SETTINGlGetIp(char *param_1);
void DWCi_SETTINGlGetNetMask(char *param_1);
void Dwci_SettinglGetGateway(char* param_1);
void Dwci_SettinglGetDnsP(char* param_1);
void Dwci_SettinglGetDnsS(char* param_1);
undefined1 Dwci_SettinglGetSetType(int param_1);
void Dwci_SettinglSetSetting(int param_1, undefined4 param_2, undefined4 param_3,
                             undefined4 param_4);
void Dwci_SettinglSet(void);
void Dwci_SettinglSetRaku(undefined4* param_1);
void Dwci_SettinglSetAoss(undefined4* param_1);
undefined4 DWCi_SETTINGlGetMemMap(void);
void Dwci_SettinglErasePage(int param_1);
void Dwci_SettinglEraseAll(void);
struct ssize_t Setting_Write(int __fd,void *__buf,size_t __n);
void Dwci_SettinglConvAddress(int param_1, int param_2, undefined4 param_3, undefined4 param_4);
int Setting_Ascii2Hex(unsigned int param_1);
void Dwci_SndlInit(void);
void Dwci_SndlEnd(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_SndlPlay(undefined4 param_1);
void Dwci_SndlSetVolume(undefined4 param_1);
void Dwci_SndlSetPitch(undefined4 param_1, undefined4 param_2);
void Dwci_SndlStop(void);
void Nns_SndMainVeneer(void);
void Dwci_SteplBegin(int param_1);
void Step_TaskBegin0(undefined4 param_1);
void Step_TaskBegin1(undefined4 param_1);
void Step_TaskBegin2(undefined4 param_1);
void Step_TaskBegin3(undefined4 param_1);
void Step_TaskBegin4(undefined4 param_1);
void Step_TaskBegin5(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SteplEnd(void);
void Dwci_SteplChange(int param_1);
bool Dwci_SteplGet(void);
void Step_TaskEnd0(undefined4 param_1);
void Step_TaskEnd1(undefined4 param_1);
void Step_TaskEnd2(undefined4 param_1);
void Step_TaskEnd3(undefined4 param_1);
void Step_TaskEnd4(undefined4 param_1);
bool Dwci_SteplIsEnd(void);
void Dwci_SteplChangeScr(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Step_TaskChange(undefined4 param_1);
undefined4 Dwci_UsbaplBegin(undefined4 param_1);
bool UsbAp_StartScan(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_UsbaplEnd(void);
void Dwci_UsbaplSetCallback(undefined4 param_1);
void UsbAp_CbWm(int16_t *param_1);
void UsbAp_ScanFirst(int param_1);
void UsbAp_ScanWait(int param_1);
void UsbAp_TaskFirst(undefined4 param_1);
void Dwci_WinlInitEx(undefined4 param_1, int param_2, int param_3, undefined4 param_4,
                     undefined4 param_5);
void Dwci_WinlEnd(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
int Dwci_WinlGet(void);
bool Dwci_WinlIsInit(void);
void Window_TaskV(undefined4 param_1);
void Window_TaskMove(undefined4 param_1);
void Window_TaskMain(void);
void Window_TaskMain1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Window_Disp(unsigned int param_1);
void Window_DispCell(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Window_PushButton(int param_1);
void Window_TaskEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Window_TaskEnd1(undefined4 param_1);
void Window_TaskEnd2(undefined4 param_1);
void Window_TaskEnd3(undefined4 param_1);
void Dwci_Mov_Mbp_MemInit(int param_1);
void DWCi_MOV_MBP_Init(undefined4 param_1,undefined4 param_2);
void Dwci_Mov_Mbp_Start(undefined4 param_1, undefined4 param_2);
undefined4 Dwci_Mov_Mbp_RegistFile(int* param_1);
void Dwci_Mov_Mbp_AcceptChild(unsigned int param_1, undefined4 param_2, undefined4 param_3,
                              undefined4 param_4);
void Dwci_Mov_Mbp_KickChild(unsigned int param_1, undefined4 param_2, undefined4 param_3,
                            undefined4 param_4);
void Dwci_Mov_Mbp_StartDownload(unsigned int param_1, undefined4 param_2, undefined4 param_3,
                                undefined4 param_4);
void Dwci_Mov_Mbp_StartDownloadAll(void);
undefined4 Dwci_Mov_Mbp_IsBootableAll(void);
void Dwci_Mov_Mbp_StartRebootAll(void);
void Dwci_Mov_Mbp_Cancel(void);
void ParentStateCallback(unsigned int param_1,undefined4 param_2,uint16_t *param_3);
void Dwci_Mov_Mbp_ChangeState(undefined2 param_1);
undefined2 Dwci_Mov_Mbp_GetState(void);
undefined2 Dwci_Mov_Mbp_GetChildBmp(int param_1);
undefined4 Dwci_Mov_Mbp_GetChildState(unsigned int param_1, undefined4 param_2, undefined4 param_3,
                                      undefined4 param_4);
int Dwci_Mov_Mbp_GetChildInfo(unsigned int param_1);
undefined2 Dwci_Mov_Mbp_GetPlayerNo(char* param_1);
void Dwci_Mov_WH_MemInit(int param_1);
void Dwci_Mov_WH_ChangeSysState(undefined4 param_1);
void Dwci_Mov_WH_SetError(undefined4 param_1);
undefined4 Dwci_Mov_WH_StateInSetParentParam(void);
void Dwci_Mov_WH_StateOutSetParentParam(int param_1);
undefined4 Dwci_Mov_WH_StateInSetParentWepKey(void);
void Dwci_Mov_WH_StateOutSetParentWepKey(int param_1);
undefined4 Dwci_Mov_WH_StateInStartParent(void);
void Dwci_Mov_WH_StateOutStartParent(int param_1, undefined4 param_2, undefined4 param_3,
                                     undefined4 param_4);
undefined4 Dwci_Mov_WH_StateInStartParentMP(void);
void Dwci_Mov_WH_StateOutStartParentMP(int param_1, undefined4 param_2, undefined4 param_3,
                                       undefined4 param_4);
undefined4 Dwci_Mov_WH_StateInStartParentKeyShare(void);
undefined4 Dwci_Mov_WH_StateInEndParentKeyShare(void);
undefined4 Dwci_Mov_WH_StateInEndParentMP(void);
void Dwci_Mov_WH_StateOutEndParentMP(int param_1);
undefined4 Dwci_Mov_WH_StateInEndParent(void);
undefined4 Dwci_Mov_WH_StateInEndChildKeyShare(void);
undefined4 Dwci_Mov_WH_StateInEndChildMP(void);
void Dwci_Mov_WH_StateOutEndChildMP(int param_1);
undefined4 Dwci_Mov_WH_StateInEndChild(void);
undefined4 Dwci_Mov_WH_StateInReset(void);
void Dwci_Mov_WH_StateOutReset(int param_1);
void Dwci_Mov_WH_StateOutEnd(int param_1);
void Dwci_Mov_WH_SetGgid(undefined4 param_1);
undefined2 Dwci_Mov_WH_GetBitmap(void);
undefined4 Dwci_Mov_WH_GetSystemState(void);
undefined4 Dwci_Mov_WH_StartMeasureChannel(void);
undefined2 Dwci_Mov_WH_StateInMeasureChannel(unsigned int param_1);
void Dwci_Mov_WH_StateOutMeasureChannel(int param_1);
void WHi_MeasureChannel(undefined4 param_1, undefined4 param_2);
undefined2 Dwci_Mov_WH_GetMeasureChannel(void);
int SelectChannel(unsigned int param_1);
bool Dwci_Mov_WH_Initialize(void);
undefined4 Dwci_Mov_WH_StateInInitialize(void);
void Dwci_Mov_WH_StateOutInitialize(int param_1);
undefined4 Dwci_Mov_WH_ParentConnect(int param_1, undefined2 param_2, undefined2 param_3);
void Dwci_Mov_WH_GetSharedDataAdr(undefined4 param_1);
undefined4 Dwci_Mov_WH_StepDS(undefined4 param_1);
void Dwci_Mov_WH_Reset(void);
void Dwci_Mov_WH_Finalize(void);
undefined4 Dwci_Mov_WH_End(void);
void Dwci_MovInit(int param_1, undefined4* param_2);
undefined4 Dwci_MovFinalize(void);
void Dwci_MovPrepare(void);
undefined4 Dwci_MovStartAdmitChild(void);
undefined4 Dwci_MovStartDownloadandBootChildVeneer(void);
void Dwci_MovFramework(void);
void Dwci_MovGetStatus(undefined1* param_1, undefined4 param_2);
void Dwci_MovSearchChannel(void);
void Dwci_MovStartWaitChild(void);
void Dwci_Mov_WaitandDownloadandBoot_Child(void);
void Dwci_Mov_ReadyMovUserID(void);
void Dwci_Mov_MovUserID(void);
void Dwci_Mov_EraseFlashData(void);
void Dwci_MovEnd(void);
undefined4 JudgeConnectableChild(int param_1);
void Parent_InitDataShare(void);
void Parent_StepDataShare(undefined2 param_1, undefined2 param_2, undefined4* param_3);
void Parent_Data_Receive_Progress(void);
undefined2 Parent_Get_Child_Data_Kind(void);
void Dwci_ArclInit(void);
void Dwci_ArclEnd(void);
undefined4 Archive_UserProc(undefined4 param_1,int param_2);
undefined4 Archive_CbRead(struct fs_archive *param_1,undefined4 param_2,int param_3,undefined4 param_4);
void Archive_CbReadRom(undefined4 param_1);
undefined4 Archive_CbWrite(void);
unsigned int* Dwci_ArclReadEx(char* param_1, unsigned int* param_2, int param_3);
void Dwci_ArclRelease(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                      undefined4 param_4);
bool Archive_CmpBack(char *param_1,char *param_2,int param_3,undefined4 param_4);
void Dwci_CelllInit(void);
void Dwci_CelllEnd(void);
int Dwci_CelllForm(int param_1, int param_2, int param_3, undefined4 param_4);
void Dwci_CelllDelete(unsigned int param_1);
int DWCi_CELLlGetObj(int param_1,int param_2);
undefined1 DWCi_CELLlSetAttr(int param_1);
void Dwci_CelllSetEffect(int param_1, int param_2, unsigned int param_3, int param_4);
void Dwci_CelllSetPalette(int param_1, int param_2, int param_3, int param_4);
void Dwci_CelllSetPosition(int param_1, int param_2, int param_3, unsigned int param_4);
void Dwci_CelllSetPriority(int param_1, int param_2, int param_3);
void Dwci_CelllGetPosition(int param_1, int param_2, unsigned int* param_3, unsigned int* param_4);
void Dwci_CeinlRead(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_CeinlRelease(int param_1);
void Dwci_CeinlSet(int param_1, int param_2, int param_3);
undefined4 Dwci_CeinlSetExObj(undefined4 param_1, undefined4 param_2);
undefined4 Dwci_CeinlSetExCell(int param_1, int param_2);
void Dwci_QuelForm(int param_1);
void Dwci_QuelFormEx(int param_1, int param_2, int param_3);
void Dwci_QuelDelete(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                     undefined4 param_4);
void Dwci_QuelPushBack(uint16_t* param_1, undefined4 param_2);
undefined4 Dwci_QuelPopBack(uint16_t* param_1);
void Dwci_EfflInit(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void DWCi_EFFlEnd(void);
undefined1 Dwci_EfflCheck(int param_1);
undefined4 Dwci_EfflFade(int param_1, int param_2, undefined4 param_3, undefined4 param_4);
void Effect_TaskFade(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_EfflWait(undefined2 param_1, undefined4 param_2, undefined4 param_3,
                         undefined4 param_4);
void Effect_TaskWait(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
void Dwci_FntlInit(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_FntlEnd(void);
int Dwci_FntlFormEx(int param_1, int param_2, int param_3, undefined4 param_4, undefined4* param_5,
                    int param_6);
void Dwci_FntlDelete(int param_1);
int Dwci_FntlFormBgEx(int param_1, int param_2);
void Effect_TaskLoad(undefined4 param_1,char *param_2);
void Dwci_FntlDeleteBg(int param_1);
void Dwci_FntlDeleteBgLcd(int param_1);
void Dwci_FntlDraw(int param_1);
void Dwci_FntlDrawCharEx(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                         undefined4 param_4, undefined2 param_5, int param_6);
void Dwci_FntlDrawStringEx(undefined4 param_1, int param_2, undefined4 param_3, undefined4 param_4,
                           int param_5, uint16_t* param_6, int param_7);
void Dwci_FntlDrawRect(int param_1);
void Dwci_FntlClear(int param_1);
void Dwci_FntlDisp(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4,
                   undefined4 param_5);
void Dwci_FntlRenewBg(int param_1);
void DWCi_InputCoord(undefined2 param_1,undefined2 param_2,undefined2 *param_3);
void Dwci_InputRect(undefined2 param_1, undefined2 param_2, undefined2 param_3, undefined2 param_4,
                    undefined2* param_5);
void Dwci_Coord2Rect(int16_t* param_1, int16_t* param_2, int16_t* param_3);
void Dwci_GXlVisible(int param_1, unsigned int param_2);
void Dwci_GXlInvisible(int param_1, unsigned int param_2);
void Dwci_GXlSetWndPosition(int param_1, int param_2, int16_t* param_3);
void Dwci_GXlSetWndPlane(int param_1, undefined4 param_2, int param_3, int param_4);
void Dwci_HeaplInit(int8_t* param_1);
void Dwci_HeaplEnd(void);
void* Dwci_HeaplAlloc(undefined4 param_1, undefined4 param_2);
int8_t* Dwci_HeaplAllocEx(unsigned int param_1);
void Dwci_HeaplFree(int* param_1);
void DWCi_HEAPlFree2(void *param_1);
void Dwci_IptlInit(void);
void Dwci_IptlEnd(void);
void Dwci_IptlRead(void);
void Input_ReadKey(void);
void Input_ReadTouch(void);
bool DWCi_IPTlCheck_Key(unsigned int param_1);
bool DWCi_IPTlCheckTrigger_Key(unsigned int param_1);
bool DWCi_IPTlCheckRepeat_Key(unsigned int param_1);
bool DWCi_TPlCheck(uint16_t *param_1);
bool DWCi_TPlCheckTrigger(uint16_t *param_1);
bool DWCi_TPlCheckRepeat(uint16_t *param_1);
bool DWCi_TPlCheckRelease(uint16_t *param_1);
void DWCi_TPlCheckATrigger(int16_t *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 DWCi_TPlGet(undefined2 *param_1);
void Dwci_IptlCheckFold(void);
void Dwci_ItrlIntr(void);
void Dwci_ItrlEnd(void);
void Interrupt_IntrVBlank(void);
void Dwci_LstlForm(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_LstlDelete(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                     undefined4 param_4);
void Dwci_LstlErase(int* param_1);
void Dwci_LstlInsert(int* param_1, int* param_2);
void DWCi_LSTlPopBack(int param_1,int *param_2);
void DWCi_LSTlPopFront(int param_1,int *param_2);
void Dwci_ObjlInit(void);
void Obj_TaskTransfer(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_ObjlEnd(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
undefined4 Dwci_ObjlFormGx(int param_1);
void Dwci_ObjlDelete(unsigned int* param_1);
int Dwci_ObjlGetOam(int param_1, int param_2);
void Dwci_OvrlInit(void);
int Dwci_OvrlAlloc(int param_1, int param_2, int param_3, unsigned int* param_4);
void Dwci_OvrlFree(unsigned int param_1);
int Dwci_StrlNLen(int param_1, int param_2);
void Dwci_ClearVram(void);
void DWCi_RepairVram(void);
void Sub_ClearVram(void);
void Dwci_SetLedWireless(void);
void DWCi_SetLedNormal(void);
void Dwci_TsklInit(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Dwci_TsklEnd(void);
void Dwci_TsklAct(int param_1);
void Dwci_TsklForm(void);
int Task_FormTask(int param_1,undefined4 param_2,undefined4 param_3,unsigned int param_4,undefined1 param_5);
void DWCi_TSKlChangeFunc(int param_1,undefined4 param_2);
void Dwci_TsklDelete(int param_1, undefined4 param_2);
void DWCi_TSKlDeleteEx(int param_1,int param_2);
void Task_DeleteTcb(int param_1,int param_2);
void Dwci_TsklOperate(int param_1, undefined1 param_2);
undefined1 Dwc_Init(undefined4 param_1);
undefined4 Nhttp_Startup(void** param_1, void** param_2, undefined4 param_3);
void Nhttpi_CleanupThreadProc(void** param_1);
undefined4 AddHdrList(int* param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
int* Nhttpi_GetHdrFromList(int* param_1);
int IncAscii(char param_1);
undefined4 CheckTagPost(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Nhttp_AddHeaderField(int* param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
int Nhttp_AddPostDataAscii(int* param_1, undefined4 param_2, undefined4 param_3);
bool Nhttp_SetCaChain(int* param_1, int param_2, int param_3);
int Nhttpi_SetReqQueue(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
int Nhttpi_FindReqQueue(int param_1);
undefined4 Nhttpi_FreeReqQueue(void);
void Nhttpi_AllFreeReqQueue(void);
undefined4 Nhttpi_InitLockReqList(void);
void ret_0215e1f4(void);
undefined4 Nhttpi_CreateCommThread(undefined4 param_1, int param_2);
void Nhttpi_DestroyCommThread(void);
void Nhttpi_KickCommThread(void);
void SetupGetcharFromHdrRecvBuf(int param_1, unsigned int param_2, undefined4* param_3,
                                unsigned int* param_4);
int GetcharFromHdrRecvBuf(int param_1, int* param_2, int* param_3);
int Nhttpi_FindNextLineHdrRecvBuf(undefined4 param_1, int param_2, int param_3, int* param_4);
int Nhttpi_SkipSpaceHdrRecvBuf(undefined4 param_1, int param_2, int param_3);
int Nhttpi_CompareTokenN_HdrRecvBuf(undefined4 param_1, int param_2, int param_3, char* param_4,
                                    int param_5);
undefined4 Nhttpi_LoadFromHdrRecvBuf(int* param_1, int param_2, int param_3, int param_4);
bool Nhttpi_IsRecvBufFull(int param_1, unsigned int param_2);
void Nhttpi_RecvBuf(int param_1, undefined4 param_2, int param_3, undefined4 param_4);
undefined4 Nhttpi_RecvBufN(int param_1, undefined4 param_2, int param_3, int param_4);
int Nhttp_CreateRequest(int param_1, unsigned int param_2, undefined4 param_3, int param_4,
                        undefined4 param_5, undefined4 param_6);
void Nhttp_DestroyRequest(int param_1);
void DeleteStrList(int* param_1);
undefined4 Nhttpi_DestroyRequestObject(int param_1);
int Nhttp_SendRequestAsync(int* param_1);
void Nhttpi_CancelAllRequests(void);
unsigned int Nhttpi_ResolveHostname(int param_1, undefined4 param_2, undefined4 param_3,
                                    unsigned int param_4);
void Nhttp_DestroyResponse(int param_1);
int Nhttpi_GetHeaderValue(int* param_1, undefined4 param_2, int* param_3);
int Nhttp_GetHeaderField(int param_1, undefined4 param_2, undefined4* param_3, undefined4 param_4);
undefined4 Nhttp_GetBodyAll(int param_1, undefined4* param_2);
void Nhttpi_SetSsLseed(void);
int Nhttpi_SocOpen(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Nhttpi_SocCloseWait(undefined4 param_1, int param_2);
undefined4 Nhttpi_SocConnect(int param_1, int param_2, socklen_t param_3,
                             unsigned int param_4);
struct ssize_t Nhttpi_SocRecv(int param_1, int param_2, void* param_3, size_t param_4,
                              int param_5);
struct ssize_t Nhttpi_SocSend(int param_1, int param_2, void* param_3, size_t param_4,
                              int param_5);
void Nhttpi_SocCancel(undefined4 param_1, int param_2, undefined4 param_3, undefined4 param_4);
int Nhttpi_Strnicmp(char* param_1, char* param_2, int param_3);
void Std_GetStringLengthVeneer(void);
void Nhttpi_Memclr(int8_t* param_1, unsigned int param_2);
void Nhttpi_Memcpy(undefined4* param_1, undefined4* param_2, unsigned int param_3);
undefined4 Nhttp_GetProgress(undefined4* param_1, undefined4* param_2);
int SaveBuf(int param_1, undefined4 param_2, int* param_3, int param_4, int param_5);
int SkipLineBuf(undefined4 param_1, undefined4 param_2);
void FreeSslConnection(int param_1);
void PutSocketToCloseQue(undefined4 param_1, int* param_2);
void ClearCloseQue(void);
int Nhttpi_GetUrlEncodedSize(char* param_1);
undefined4 Nhttpi_EncodeUrlChar(undefined1* param_1, unsigned int param_2);
int Nhttpi_StrToHex(char* param_1, int param_2);
int Nhttpi_StrToInt(int param_1, int param_2);
int Nhttpi_IntToStr(int param_1, unsigned int param_2);
undefined4 Nhttpi_CompareToken(char* param_1, char* param_2);
int Nhttpi_Strtonum(char* param_1, int param_2);
undefined4 Nhttpi_Memfind(int param_1, int param_2, char* param_3, int param_4);
void Dwci_Ndi_FreeAttr(void);
undefined4 SetAttr(int param_1, char* param_2);
undefined4 Dwci_NdSetAttr(undefined4 param_1, undefined4 param_2, undefined4 param_3);
int GetNchar(char* param_1, char* param_2, int param_3);
int DecodeChar(unsigned int param_1);
int Dwci_Ndi_GetEncodeLenBase64(int param_1);
int Dwci_Ndi_EncodeBase64(char* param_1, int param_2, int param_3, unsigned int param_4);
int StrAlloc(undefined4 param_1);
undefined4 Dwci_NdStartup(undefined4 param_1, void** param_2, undefined4 param_3,
                          undefined4 param_4, undefined4 param_5, undefined4 param_6,
                          undefined4 param_7);
void NhttpCleanupCallback(void);
void Dwci_NdCleanupAsync(undefined4 param_1);
undefined4 Dwci_Ndi_GetDSdesc(undefined4 param_1, undefined4 param_2);
void Dwci_Ndi_GetUserAgent(undefined4 param_1);
void Req_Callback(int param_1, undefined4 param_2, int param_3, undefined4 param_4);
void FreeHttp(undefined4 param_1, undefined4 param_2);
undefined4 SetupHttp(int* param_1, int* param_2, undefined4 param_3, undefined4 param_4,
                     undefined4 param_5);
undefined4 RunHttp(int* param_1, undefined4 param_2);
bool Dwci_NdGetFileListNumAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                                undefined4 param_4);
undefined4 Dwci_NdGetFileListAsync(undefined4 param_1, undefined4 param_2, int param_3);
undefined4 Dwci_NdGetFileAsync(int param_1, undefined4 param_2, unsigned int param_3,
                               undefined4 param_4);
undefined4 Nhttp_GetProgressVeneer(undefined4* param_1, undefined4* param_2);
bool Dwci_Ndi_Response_Count(undefined4 param_1, int param_2, undefined4 param_3,
                             undefined4 param_4);
bool Dwci_Ndi_Response_Contents(undefined4 param_1, int param_2, undefined4 param_3,
                                undefined4 param_4);
undefined4 Dwci_Ndi_InitLockGlobal(void);
void ret_021626e0(void);
undefined4 Dwci_Ndi_InitHttpCallback(void);
void ret_02162734(void);
bool Dwci_Ndi_PrepareHttpCallback(undefined4 param_1, int param_2);
void Dwci_Ndi_UnprepareHttpCallback(undefined4 param_1, int param_2);
void Dwci_Ndi_KickThread(undefined4 param_1);
void Dwci_Ndi_GetMacAddress(undefined4 param_1);
void Std_CompareNStringVeneer(void);
void Dwci_Ndi_Memclr(int8_t* param_1, unsigned int param_2);
void Dwci_Ndi_Memcpy(undefined4* param_1, undefined4* param_2, unsigned int param_3);
int Nhttpi_StrToIntVeneer(int param_1, int param_2);
int Nhttpi_IntToStrVeneer(int param_1, unsigned int param_2);
int Dwci_Ndi_HexToStrFigure(int param_1, unsigned int param_2, int param_3);
#endif