#ifndef HEADERS_FUNCTIONS_OVERLAY11_H_
#define HEADERS_FUNCTIONS_OVERLAY11_H_

struct c_ranger_net_scene * CRangerNetSceneConstructor(struct c_ranger_net_scene *this,struct megastruct *param_2);
void CRangerNetSceneInit(struct c_ranger_net_scene *param_1);
void ret_0211d860(void);
struct c_ranger_net_agb_scene * CRangerNetAgbSceneConstructor(struct c_ranger_net_agb_scene *this);
void ret_0211df48(void);
void ret_0211df4c(void);
void ret_0211df50(void);
void ret_0211df58(void);
void ret_0211df5c(void);
void ret_0211df60(void);
struct ov_11_unk_struct_0x730 *Ov110x730Constructor(struct ov_11_unk_struct_0x730 *this,struct megastruct * megastruct_ptr,int param_3);
void Ov110x730InitPrimary(struct ov_11_unk_struct_0x730 *this);
void Ov110x730InitSecondaryVeneer(struct ov_11_unk_struct_0x730 *this);
void Ov110x730InitSecondary(struct ov_11_unk_struct_0x730 *param_1);
void MaybeFreeRangerNetScene(struct ov_11_unk_struct_0x730 *param_1);
void ret_021245a4(void);
int Return0x2700(void);
void ret_02126964(void);
void ret_02126968(void);
void ret_0212697c(void);
void ret_02126980(void);
void ret_02126984(void);
struct ov_11_unk_struct_0x3ec *Ov110x3ecConstructor(struct ov_11_unk_struct_0x3ec *this,struct megastruct * megastruct_ptr_ptr,struct ov_11_unk_struct_0x730 *parent);
int MaybeInitRsaKeyFileData(int param_1,char *param_2,undefined4 param_3,undefined4 param_4);
void ret_0212d978(void);
struct ov_11_unk_struct_0x198 *Ov110x198Constructor(struct ov_11_unk_struct_0x198 *this,struct ov_11_unk_struct_0x730 *parent);
struct ov_11_unk_struct_0x18 * Ov110x18Constructor(struct ov_11_unk_struct_0x18 *param_1,struct megastruct * megastruct_ptr);
struct ov_11_unk_struct_0x4e4 *Ov110x4e4Constructor(struct ov_11_unk_struct_0x4e4 *param_1,struct megastruct * megastruct_ptr_ptr,struct ov_11_unk_struct_0x18 *param_3,struct ov_11_unk_struct_0x730 *param_4);
struct ov_11_unk_struct_2 * Overlay11EntryPoint2(struct ov_11_unk_struct_2 *param_1);
void ret_0213201c(void);
void ret_02132020(void);
undefined4 Dwc_AC_Process(void);
void Dwc_AC_GetStatus(void);
undefined1 Dwc_AC_GetApType(void);
undefined4 Dwc_AC_Destroy(void);
void Dwci_AC_InsertApInfo(int param_1,undefined4 param_2);
void Dwci_AC_Alloc(unsigned int param_1,undefined4 param_2);
struct unk_wifi_struct_0x18 * Dwci_AC_GetMemPtr(unsigned int param_1);
void Dwci_AC_SetPhase(unsigned int param_1);
undefined1 MaybeGetWfcInitCase(void);
void Dwci_AC_SetError(undefined4 param_1);
undefined4 Dwci_AC_GetError(void);
unsigned int Dwci_ConvConnectApType(unsigned int param_1);
void Free_Disused(void);
undefined4 CheckDuplicate(void);
undefined4 Dwci_AC_CheckNintendoSsid(int param_1);
unsigned int CompareList(int param_1,int param_2,int param_3);
unsigned int CompareListDiff(int param_1,int param_2);
int AddList(undefined1 param_1,int param_2,undefined4 param_3,int param_4);
void SetDataListTail(undefined1 param_1,int param_2,int8_t param_3,int param_4);
void UpDateList(int param_1,int param_2,int8_t param_3,int param_4);
void SortList(int param_1,int param_2);
void Dwci_AC_CallBackWcm(int16_t *param_1);
int Dwci_AC_ConnectAP(void);
undefined4 ConnectStart(int param_1);
undefined4 ConnectAP(int param_1);
unsigned int GetConnectType(int param_1);
undefined4 GetPowerMode(int param_1);
undefined4 GetAuthMode(int param_1);
undefined4 Dwci_AC_CloseNetwork(int8_t *param_1);
undefined4 DisConnectAP(void);
bool CloseSocket(void);
undefined4 Dwci_AC_Error(void);
void Dwci_AC_GetResult(void);
undefined4 GetProgramaError(undefined4 param_1);
undefined4 GetNotFoundAP(int param_1);
undefined1 Dwci_AC_MakeSearchList(int param_1);
undefined4 Dwci_AC_CheckFreespot(int param_1);
unsigned int MakeAroundList(int param_1);
unsigned int MakeStealthList(int param_1);
char MakeUserList(int param_1);
char MakeDifferChannelList(int param_1);
unsigned int CheckDifferChannelStart(int param_1);
int8_t Dwci_AC_ConnectRetryAP(void);
int Dwci_AC_SearchAP(void);
void Dwci_AC_SetStealthChannel(unsigned int param_1);
int Dwci_AC_GetStealthChannel(unsigned int param_1);
void Dwci_AC_SearchReStart(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 SearchStart(int param_1);
undefined4 SearchAround(int param_1);
undefined4 SearchAround2ndLap(int param_1);
undefined4 SearchDifferChannel(int param_1);
undefined4 SearchStealth(int param_1);
int NextSearchCheck(int param_1,int param_2);
int SearchEndCheck(unsigned int param_1,int param_2);
undefined4 CheckStartStealthSearch(int param_1);
void ScanStart(undefined4 param_1,undefined4 param_2,int param_3,unsigned int param_4);
undefined4 Dwci_AC_Start(void);
int Dwci_AC_ConnectTest(void);
undefined4 ConnectTestStart(undefined4 param_1);
undefined4 GetIpAddress(int param_1);
undefined4 ConnectTestCreate(void);
undefined4 ConnectTestProcess(int param_1);
undefined4 ConnectTestEnd(int param_1);
undefined4 ConnectTestRetry(void);
void MakeSocConfig(undefined4 *param_1,int param_2,undefined4 *param_3);
unsigned int ConvAddress(int8_t *param_1);
unsigned int ConvNetMask(int param_1);
void CheckSetDns(int param_1);
bool Dwci_AC_CheckNintendoShopAP(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_AC_GetNintendoShopWepKey(undefined4 param_1,undefined4 param_2);
void Dwci_AC_GetPostalCode(undefined4 param_1,undefined4 *param_2);
bool Dwci_AC_CheckNintendoUsbAP(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DecodeSsid(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
void MakeShopWepKey(undefined4 param_1,undefined4 *param_2);
void MakeUsbWepKey(int param_1,undefined4 *param_2);
int Codetovalue(unsigned int param_1);
unsigned int Db64(int param_1,int param_2,unsigned int param_3,unsigned int param_4);
void Dwc_Auth_SetCustomNas(char *param_1);
int Dwc_Auth_Create(undefined4 *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_Auth_StartThread(void);
void Dwc_Auth_Abort(undefined4 param_1,int param_2);
void Dwc_Auth_Destroy(void);
undefined4 Dwc_Auth_GetError(undefined4 param_1,int param_2);
void Dwc_Auth_GetResult(int *param_1);
undefined4 Dwci_Auth_Start(int param_1);
void Dwci_Auth_Thread(void);
undefined4 Dwci_Auth_ParseHttp(void);
undefined4 Dwci_Auth_FillResult(void);
undefined4 Dwci_Auth_Prepare_FirstPost(undefined4 param_1,char *param_2,undefined4 param_3,undefined4 param_4);
void Dwci_Auth_SetError(undefined4 param_1);
void Dwc_Auth_GetCalInfoFromNVram(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
bool Dwc_Auth_SetCalInfoToHttp(undefined4 param_1,char *param_2,int param_3);
undefined4 Dwc_Http_Create(int8_t *param_1,undefined4 *param_2);
undefined4 Dwc_Http_FinishHeader(int param_1);
void Dwc_Http_StartThread(int param_1,undefined4 param_2);
void Dwc_Http_Abort(int param_1,int param_2);
undefined4 Dwci_Http_Yield(int param_1,int param_2);
void Dwci_Http_InitCpsSocket(int param_1);
void Dwci_Http_Resolve(int param_1);
undefined4 Dwci_Http_CheckHeaderReceived(int param_1);
void Dwci_Http_Thread(int param_1);
void Dwc_Http_Destroy(int8_t *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_Http_WriteBasicHeader(int param_1);
undefined4 Dwc_Http_Add_HeaderItem(int param_1,char *param_2,char *param_3);
undefined4 Dwc_Http_Add_PostBase64Item(int param_1,char *param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwc_Http_Add_Body(int param_1,char *param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_Http_AllocBuffer(int param_1,int *param_2,int param_3,undefined4 param_4);
void Dwci_Http_FreeBuffer(int param_1,int *param_2);
undefined4 Dwci_Http_ReallocBuffer(int param_1,int *param_2,int param_3,undefined4 param_4);
undefined4 Dwci_Http_SetHostinfo(int param_1,char *param_2);
undefined4 Dwci_Http_AddResult(int param_1,int *param_2,char *param_3,char *param_4);
undefined4 Dwc_Http_ParseResult(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwc_Http_GetResult(int param_1,char *param_2);
void Dwc_Http_GetBase64DecodedResult(undefined4 param_1,undefined4 param_2,int param_3,unsigned int param_4);
undefined4 Dwc_Http_GetRawResult(undefined4 param_1,undefined4 param_2,char *param_3,int param_4);
void Dwci_Http_DestroyResult(int param_1,int param_2,int param_3);
undefined4 Dwc_Netcheck_Create(undefined4 *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwc_Netcheck_Destroy(void);
void Dwc_Netcheck_Abort(void);
undefined4 Dwc_Netcheck_GetError(undefined4 param_1,int param_2);
undefined4 Dwc_Netcheck_GetReturnCode(void);
void Dwci_Netcheck_StartThread(void);
void Dwci_Netcheck_SetError(undefined4 param_1);
undefined4 Dwc_Auth_SetNasTimeDiff(char *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwc_Svl_Init(void* *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwc_Svl_Cleanup(void);
undefined4 Dwc_Svl_GetTokenAsync(undefined4 param_1,int8_t *param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwc_Svl_Process(void);
undefined4 Dwci_Svl_ParseHttp(void);
unsigned int Dwc_Auth_Base64Encode(undefined4 *param_1,unsigned int param_2,int param_3,unsigned int param_4);
int8_t * Dwc_Auth_Base64Decode(int param_1,unsigned int param_2,int8_t *param_3,int8_t *param_4);
void Dwci_BM_GetWiFiInfo(undefined4 *param_1);
bool Dwci_BM_SetWiFiInfo(undefined4 param_1,int param_2);
undefined4 Dwci_BackuplInit(uint16_t *param_1);
bool Dwci_BackuplRead(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
bool Dwci_BackuplWritePage(int param_1,int param_2,undefined4 param_3);
bool Dwci_BackuplWriteAll(int param_1);
void Dwci_BackuplSetWiFi(undefined4 *param_1);
char Dwci_BackuplConvMaskCidr(int param_1);
void Dwci_BackuplConvMaskAddr(unsigned int param_1,int param_2);
undefined4 Dwc_BackuplCheckSsid(int param_1);
bool Dwc_BackuplCheckIp(undefined4 *param_1,undefined4 *param_2,undefined4 param_3,undefined4 param_4);
bool Dwc_BackuplCheckAddress(int8_t *param_1);
bool Verify(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
uint16_t Callback_NVram(undefined4 param_1,uint16_t param_2,int param_3);
undefined * Dwci_BackuplConvWifiInfo(undefined4 *param_1);
undefined4 Dwc_BM_Init(int8_t *param_1);
undefined4 CheckAp(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Init(int16_t *param_1);
void InitPage(int param_1,int param_2);
unsigned long long Dwci_Util_WiFiId_scrambleUid(unsigned int param_1,unsigned int param_2,unsigned int param_3,unsigned int param_4);
undefined4 Dwci_Auth_GetNewWiFiInfo(undefined4 *param_1);
bool Dwci_Auth_MakeWiFiID(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
bool Dwci_Auth_UpDateWiFiID(undefined4 *param_1,undefined4 param_2);
undefined4 Dwci_Auth_RemakeWiFiID(int param_1);
bool Dwc_Auth_CheckWiFiIdNeedCreate(void);
undefined4 Dwc_GetLastError(undefined4 *param_1);
undefined4 Dwc_GetLastErrorEx(undefined4 *param_1,undefined4 *param_2);
bool Dwci_IsError(void);
void Dwci_SetError(int param_1,undefined4 param_2);
void Dwc_InitInetEx(struct DWCInetControl *inetCntl,uint16_t dmaNo,uint16_t powerMode,uint16_t ssl_priority);
void Dwc_InitInet(struct DWCInetControl *inetCntl);
void Dwc_SetAuthServer(int param_1);
bool Dwc_CheckInet(void);
void Dwc_ProcessInet(void);
undefined4 Dwc_GetInetStatus(void);
void Dwc_CleanupInet(void);
undefined4 Dwc_CleanupInetAsync(void);
undefined4 Dwci_CheckDisconnected(void);
undefined4 Dwc_UpdateConnection(void);
undefined4 Dwc_SvlgetTokenAsync(char *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int Dwc_Svlprocess(void);
undefined4 Dwc_NasloginAsync(void);
undefined4 Dwc_NasloginProcess(void);
void Dwci_NdAlloc(int param_1,undefined4 param_2);
void Dwci_NdFree(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_NdCallback(undefined4 param_1,int param_2,int param_3);
void Dwci_NdCleanupCallback(void);
void Dwci_SvltokenWaitThread(void);
undefined4 Dwc_NdInitAsync(undefined4 param_1,char *param_2,char *param_3);
undefined4 Dwc_NdCleanupAsync(undefined4 param_1);
undefined4 Dwc_NdSetAttr(undefined4 param_1,undefined4 param_2,undefined4 param_3);
undefined4 Dwc_NdGetFileListNumAsync(undefined4 param_1);
undefined4 Dwc_NdGetFileListAsync(int8_t *param_1,undefined4 param_2,int param_3);
undefined4 Dwc_NdGetFileAsync(undefined4 param_1,undefined4 param_2,undefined4 param_3);
undefined4 Dwc_NdGetProgress(undefined4 param_1,undefined4 param_2);
void Aoss_Malloc(void);
void Aoss_Free(void);
undefined4 Aossi_Init(int param_1);
void Aoss_release(void);
void Aoss_data_init(uint16_t *param_1);
undefined4 Aoss_seq_data_copy(uint16_t *param_1);
undefined4 Aoss_check_str(int8_t *param_1,int param_2);
undefined4 CheckAP(unsigned int *param_1);
undefined4 Aoss_set_ApInfo(undefined4 *param_1);
void MakeSendSeqID(int param_1,int param_2,undefined4 param_3);
undefined4 Aoss_StatusExclusion(int param_1);
undefined4 RecvMessage(undefined4 param_1,int param_2,int *param_3,undefined4 param_4);
int AstsSetInitRes(int param_1,int param_2,int *param_3,undefined4 param_4);
int AstsSetSecureRes(int param_1,int param_2,int *param_3,int param_4);
int AstsRestartRes(int param_1,int param_2,int *param_3,int param_4);
int DecodePacket(int param_1);
undefined4 CheckSeqID(int param_1,undefined4 param_2);
undefined4 CheckRecvSeqID(int param_1,int param_2);
undefined4 GetProductInfo(undefined1 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
int Aoss_get_bin(int param_1,int param_2);
undefined4 GetWepData(int param_1,int param_2);
undefined4 GetWpaData(int param_1,int param_2);
undefined4 GetBssidData(int param_1,undefined4 param_2);
int GetSecurityData(int param_1,char *param_2,int param_3,int param_4,int param_5);
bool GetSecurityType(unsigned int param_1);
undefined4 SendMessage(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 AstsSetInitReq(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 AstsSetSecureReq(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
undefined4 AstsRestartReq(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
int SetStaData(undefined1 *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void PacketDataSet(int param_1,undefined2 *param_2,undefined4 param_3,int16_t *param_4,undefined2 *param_5,undefined4 param_6);
void SetPacketHeader(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,undefined1 param_5,undefined1 param_6,undefined4 param_7);
void SendPacketUdp(undefined4 param_1,undefined4 param_2,int param_3,undefined4 param_4);
undefined4 EncodeRC4(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined1 *param_4,undefined4 param_5,undefined4 param_6,int param_7);
undefined4 DecodeRC4(undefined4 param_1,undefined4 param_2,undefined4 param_3,int param_4,undefined4 param_5,undefined4 param_6,int param_7);
void RC4encrypt(undefined4 param_1,int param_2,int param_3,unsigned int param_4);
int8_t Crc(undefined4 param_1,undefined4 param_2);
unsigned int Update_crc(unsigned int param_1,int param_2,int param_3,int param_4,int param_5);
void Make_crc_table(undefined4 param_1,unsigned int *param_2);
undefined4 CryptSeqNo(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
void AddKey(int param_1,int param_2,int param_3);
void Rotate(int param_1,int param_2,int param_3,undefined4 param_4);
int Aoss_Memcmp(int8_t *param_1,int8_t *param_2,int param_3);
void Aoss_Memcpy(undefined4 *param_1,undefined4 *param_2,unsigned int param_3);
void Aoss_Memset(int8_t *param_1,unsigned int param_2,unsigned int param_3);
void ret_0213e00c(void);
int SocketVeneer(int __domain,int __type,int __protocol);
unsigned int Aoss_Htonl(unsigned int param_1);
unsigned int Aoss_Htons(unsigned int param_1);
unsigned int Aoss_Ntohl(unsigned int param_1);
unsigned int Aoss_Ntohs(unsigned int param_1);
int Aoss_Strlen(char *param_1);
undefined4 Aossi_Status(void);
uint16_t * GetFrameData(uint16_t *param_1,unsigned int *param_2,unsigned int *param_3);
uint16_t * GetElementData(int *param_1,uint16_t *param_2,unsigned int *param_3,unsigned int *param_4);
void GetFirstElement(uint16_t *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SetSingleElement(int16_t *param_1);
undefined4 IsSearchCommand(undefined4 param_1,unsigned int *param_2);
void SetSearchRes(undefined4 param_1);
undefined4 AsciiToHex(int param_1,int param_2,int param_3);
void Aeskw_xor64(int8_t *param_1,int8_t *param_2,int8_t *param_3);
undefined4 rijndaelKeySetupEnc(unsigned int *param_1,int8_t *param_2,int param_3);
int rijndaelKeySetupDec(unsigned int *param_1);
void rijndaelEncrypt(unsigned int *param_1,int param_2,int8_t *param_3,undefined1 *param_4);
void rijndaelDecrypt(unsigned int *param_1,int param_2,int8_t *param_3,undefined1 *param_4);
void MY_MD5Init(undefined4 *param_1);
void MY_MD5Update(int param_1,int param_2,unsigned int param_3,undefined4 param_4);
void MY_MD5Final(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
void MD5Transform(int *param_1,undefined4 param_2);
void Encode(int param_1,undefined4 *param_2,unsigned int param_3);
void Decode(undefined4 *param_1,int param_2,unsigned int param_3);
void MD5_memcpy(int param_1,int param_2,unsigned int param_3);
void MD5_memset(undefined1 *param_1,undefined1 param_2,unsigned int param_3);
void MD5Encode(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int PutHex(char *param_1,unsigned int param_2);
int PutMac(undefined1 *param_1,char *param_2);
undefined4 Atermi_ApConfigGetState(undefined4 *param_1);
void SendNotify(void);
void Dwci_AnimelInitEx(int param_1);
void Dwci_AnimelEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void TaskAnime(void);
void Dwci_BtnlInit(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_BtnlEnd(void);
int Dwci_BtnlGet(void);
void Dwci_BtnlSet(undefined1 param_1);
void Dwci_BtnlSetForce(undefined1 param_1);
bool Dwci_BtnlIsEnd(void);
void Dwci_BtnlEnable(void);
void Dwci_BtnlDisable(void);
void Disp(int param_1);
void TaskStart(undefined4 param_1);
void TaskStart1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void TaskMain(void);
void TaskEnd(undefined4 param_1);
void TaskEnd1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void TaskRelease(undefined4 param_1);
void Dwci_CommentlInit(void);
undefined4 Dwci_CommentlDispEx(undefined4 param_1,undefined4 param_2,undefined4 param_3);
undefined4 Dwci_CommentlDelete(void);
void Dwci_Char(char *param_1);
void Dwci_CmnlLoadResource(undefined4 param_1,void* *param_2,undefined4 param_3,undefined4 param_4);
void Dwci_CmnlStep(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_CmnlButton(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_CmnlMsgDraw(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_CmnlMsgNameDraw(undefined4 param_1,undefined4 param_2);
undefined4 Dwci_CmnlFontFlag(void);
void Dwci_FocuslInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_FocuslEnd(void);
void Dwci_FocuslDisp(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_FocuslDisp4(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_FocuslDelete(void);
void Dwci_HLlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_HLlLoad(int param_1);
void Dwci_HLlLoadSet(void);
void Dwci_HLlLoadList(void);
void TaskLoad(undefined4 param_1);
void Dwci_IconlInit(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_IconlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void TaskRenew(void);
void Dwci_KBlInit(void);
void Dwci_KBlEnd(void);
undefined1 Dwci_KBlGet(void);
void Dwci_KBlSetErase(undefined1 param_1);
void Dwci_KBlSetInput(undefined1 param_1);
bool Dwci_KBlIsInit(void);
void TaskStart0(undefined4 param_1);
void TaskStart1(undefined4 param_1);
void TaskStart2(undefined4 param_1);
void TaskStart3(undefined4 param_1);
void TaskStart4(undefined4 param_1);
void TouchTriger(void);
void TouchRelease(void);
void PushCaps(void);
void PushShift(void);
void Touch(void);
void ExchangeBack(int param_1);
void Key(void);
void Disp(int param_1,int param_2,unsigned int param_3,undefined4 param_4);
void ChangePage(int param_1);
void ChangeColor(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
void DispFocus(void);
void MoveFocus(int param_1);
void TaskEnd0(undefined4 param_1);
void TaskEnd1(undefined4 param_1);
void TaskEnd2(undefined4 param_1);
void TaskEnd3(undefined4 param_1);
void TaskEnd4(undefined4 param_1);
void TaskEnd5(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_KB10lInit(void);
void Dwci_KB10lEnd(void);
undefined1 Dwci_KB10lGet(void);
void Dwci_KB10lSetErase(undefined1 param_1);
void Dwci_KB10lSetInput(undefined1 param_1);
void Dwci_KB10lSetShift(undefined1 param_1);
bool Dwci_KB10lIsInit(void);
void TaskStart0(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void TaskStart1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void TaskStart2(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void TaskStart3(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void TaskStart4(undefined4 param_1);
void TouchTriger(void);
void TouchRelease(void);
void Touch(void);
void ExchangeBack(int param_1);
void Key(void);
void Disp(int param_1,unsigned int param_2);
void ChangeColor(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
void DispFocus(void);
void MoveFocus(int param_1);
void TaskEnd0(undefined4 param_1);
void TaskEnd1(undefined4 param_1);
void TaskEnd2(undefined4 param_1);
void TaskEnd3(undefined4 param_1);
void TaskEnd4(undefined4 param_1);
void TaskEnd5(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwc_StartUtility(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 CheckParam(int param_1,unsigned int param_2);
void InitGame(void);
void InitGraph(void);
void ProcEnd(void);
void Dwci_SetParam_(undefined4 param_1,undefined4 param_2);
void Dwci_GetParam_(undefined4 *param_1,undefined4 *param_2);
void Dwci_SetParam2_(undefined4 param_1,undefined4 param_2);
void Dwci_GetParam2_(undefined4 *param_1,undefined4 *param_2);
unsigned int Dwci_Entry(void);
bool Dwci_Flag(unsigned int param_1);
void Dwci_EndUtility(void);
char KDwci_Language(void);
void Dwci_MsglInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int * Dwci_MsglRead(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_MsglRelease(int param_1);
int Dwci_MsglGet(int *param_1,unsigned int param_2);
void Dwci_MsglGetEx(int *param_1,unsigned int param_2,int param_3,int16_t param_4);
void Dwci_MovlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_MovlEnd(void);
void TaskEnd(undefined4 param_1);
bool Dwci_MovlIsEnd(void);
void Dwci_MovlChangeCallback(undefined4 param_1);
void Dwci_MovStartDownloadandBootChild(void);
int Dwci_MovlGetChild(void);
void TaskFramework(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SceneEnd(void);
void EndScene(void);
void Dwci_SceneInit(void);
void ProcFade(void);
void ProcWait(void);
void Dwci_SceneMenu(void);
void InitGraphics(void);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_02147dbc(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void MoveFocus(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DispPushButton(void);
void Dwci_SceneOptErase(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_021481a0(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void ProcConfirm(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_02148518(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void Dwci_SceneOptInfo(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DrawInfo(void);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_02148958(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void Dwci_SceneOptMenu(void);
void InitGraphics(void);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_02148e88(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void MoveFocus(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DispPush(void);
void Dwci_SceneOptMovComm(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void ret_021492a8(void);
void ret_021492ac(void);
void EndScene(void);
void EndScene1(void);
void CbMov(int param_1);
void InitGraphics(void);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_02149538(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void Dwci_SceneOptMovComplete(void);
void InitGraphics(void);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_02149758(void);
void Button(void);
void Dwci_SceneOptMovConfirm1(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_021499ec(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void Dwci_SceneOptMovDisconnect(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void ret_02149c8c(void);
void EndScene(void);
void EndScene1(void);
void Dwci_SceneOptMovFailure(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void ProcInit2(void);
void Input(void);
void ret_02149f44(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void Dwci_SceneOptMovUser(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcScene(void);
void ret_0214a308(void);
void ret_0214a30c(void);
void EndScene(void);
void EndScene1(void);
void EndScene2(void);
bool Dwci_IsFold(void);
void Dwci_SceneOptMovWait(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_0214a660(void);
void Button(void);
void EndScene(void);
void EndScene1(void);
void EndScene2(void);
void CbMov(int param_1);
bool Dwci_IsFold(void);
void Dwci_SceneSetAossButton(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void ProcInit2(void);
void ProcScene(void);
void Input(void);
void ret_0214aba8(void);
void Button(void);
void EndScene(void);
void EndScene1(void);
void EndScene2(void);
void ProcWait(void);
void ProcCancel(void);
void Dwci_SceneSetAossComplete(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ret_0214af68(void);
void EndScene(void);
void EndScene1(void);
void Dwci_SceneSetApList(void);
void InitGraphics(void);
void InitScrollBar(void);
void GetCharName(void);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void Draw(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void DrawApInfo(void);
void DrawAp(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
void DrapApObj(int param_1,int param_2);
void SetOffset(void);
void TaskUp(undefined4 param_1);
void TaskDown(undefined4 param_1);
void TaskVBlank(void);
void DispFocus(void);
void MoveFocus(int param_1);
void ScrollUp(void);
void ScrollDown(void);
void DispPushButton(void);
void Dwci_SceneSetEdit32(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_0214ca98(void);
void EndScene(void);
void EndScene1(void);
void EndScene2(void);
void EndScene3(void);
void DrawSsid(void);
void DispCaret(void);
void ProcWin(void);
void ProcWin1(void);
bool IsCorrect(void);
void ProcError1(void);
void Dwci_SceneSetEditAddress(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
bool IsOver(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ret_0214d80c(void);
void EndScene(void);
void EndScene1(void);
void EndScene2(void);
void EndScene3(void);
void DrawAddress(void);
void DispCaret(void);
void ProcWin(void);
void ProcWin1(void);
void ArrangeAddress(void);
bool IsCorrect(void);
void ProcError1(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DrawMessage(void);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_0214e2b4(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void Dwci_SceneSetList(void);
void InitGraphics(void);
void CalcParam(void);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
undefined4 InputWinButton(void);
void PushWinButton(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void PushIpAuto(unsigned int param_1);
void PushDnsAuto(unsigned int param_1);
void Draw(void);
void EndScene1(void);
void EndScene2(void);
void DrawWindow(void);
void DrawColumnChar(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DrawColumnObj(undefined4 param_1,undefined4 param_2);
bool IsEnablePush(undefined4 param_1);
void DispObj(int param_1,int param_2,int param_3,undefined4 param_4);
void DrawString(int param_1,int param_2);
void DrawAddress(undefined1 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void SetOffset(void);
unsigned int IsPush(void);
int CalcColumnIdx(int param_1);
int CalcIdxColumn(int param_1);
void TaskUp(undefined4 param_1);
void TaskDown(undefined4 param_1);
void TaskVBlank(void);
void DispFocus(void);
void ApplyForcus(void);
void ApplyForcus1(int param_1);
void MoveFocus(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void DispPushButton(void);
void TaskPushCount(void);
void PushButtonYesNo(void);
undefined4 IsCorrect(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void ret_02150a60(void);
void ret_02150a64(void);
void EndScene(void);
void EndScene1(void);
bool Dwci_IsFold(void);
void Dwci_SceneSetRakuButton1(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_02150cbc(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void CheckRaku(void);
void ProcError(void);
bool Dwci_IsFold(void);
void Dwci_SceneSetRakuButton1(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_021510d4(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void CheckRaku(void);
void Dwci_SceneSetRakuComplete(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ret_0215148c(void);
void EndScene(void);
void EndScene1(void);
bool Dwci_IsFold(void);
void Dwci_SceneSetRakuReady(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_021517a8(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void CheckRaku(void);
void Dwci_SceneSetSearch(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void IsEnd(void);
void Input(void);
void ret_02151d30(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void Dwci_SceneSetSelectAp(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void InitGraphics(void);
void InitObj(void);
void ProcInit(void);
void ProcInit1(void);
void ProcInit2(void);
void Input(void);
void ret_0215232c(void);
void Button(void);
void EndScene(void);
void EndScene1(void);
void EndScene2(void);
void DispFocus(void);
void MoveFocus(int param_1);
void DispPushClear(void);
void ProcErase(void);
void DispPush(void);
void Dwci_SceneSetSelectWay(void);
void InitGraphics(void);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_02153088(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void MoveFocus(int param_1);
void DispPush(void);
void Dwci_SceneSetTest(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void InitAc(void);
void ProcInit(void);
void ProcInit1(void);
void ret_02153660(void);
void ret_02153664(void);
void ret_02153668(void);
void EndScene(void);
void EndScene2(void);
void TaskAc(undefined4 param_1);
void Dwci_SceneSetTestCompletet(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ret_021538e0(void);
void EndScene(void);
void EndScene1(void);
void Wait(void);
void Dwci_SceneSetTestConfirm(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void ProcScene(void);
void ret_02153c2c(void);
void ret_02153c30(void);
void EndScene(void);
void EndScene1(void);
void Dwci_SceneSetUsbComplete(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ret_02153dcc(void);
void EndScene(void);
void EndScene1(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_021540ac(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
bool Dwci_IsFold(void);
void Dwci_SceneSetUsbReady1(void);
void InitGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ProcInit(void);
void ProcInit1(void);
void Input(void);
void ret_0215446c(void);
void Button(void);
void EndScene1(void);
void EndScene2(void);
void ProcBoth(void);
void ProcBoth1(void);
void Dwci_ScreenlInit(undefined4 param_1);
void Dwci_ScreenlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_ScreenlRenew(void);
void Dwci_ScreenlCopy(int param_1,int param_2,int param_3,int param_4);
void TaskLoad(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_ScreenlCopyPalette(int param_1,int param_2,int param_3,undefined4 param_4);
void TaskCopyPltt(undefined4 param_1);
void Dwci_ScreenlSetPalette(undefined4 param_1);
void TaskSetPltt(undefined4 param_1);
void Dwci_SBlInit(int param_1,undefined1 param_2,undefined4 param_3,int param_4,int param_5);
void Dwci_SBlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined1 Dwci_SBlGet(void);
undefined1 Dwci_SBlGetState(void);
void Disp(int param_1);
void Dwci_SBlEnable(void);
void Dwci_SBlDisable(void);
void TaskMain(void);
void MoveBar(void);
void PlaySound(int param_1);
void StepBar(int param_1);
void SetBar(void);
int IsTrigger(void);
int IsTouch(void);
void CalcRect(undefined4 param_1,int16_t *param_2);
void Disp(int param_1);
void Dwci_SearchlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SearchlEnd(void);
bool Dwci_SearchlBegin(void);
bool StartScan(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
bool Dwci_SearchlStop(void);
int Dwci_SearchlGetApInfo(int *param_1);
void Callback(uint16_t *param_1);
void renewInfo(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SettignlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int Dwci_SettignlGet(void);
void Dwci_SettinglSetDnsAuto(undefined1 param_1);
void Dwci_SettinglSetSsid(undefined4 *param_1);
void Dwci_SettinglSetWep(undefined4 *param_1);
void Dwci_SettinglGetSsid(undefined4 *param_1);
void Dwci_SettinglGetGateway(char *param_1);
void Dwci_SettinglGetDnsP(char *param_1);
void Dwci_SettinglGetDnsS(char *param_1);
undefined1 Dwci_SettinglGetSetType(int param_1);
void Dwci_SettinglSetSetting(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SettinglSet(void);
void Dwci_SettinglSetRaku(undefined4 *param_1);
void Dwci_SettinglSetAoss(undefined4 *param_1);
void Dwci_SettinglErasePage(int param_1);
void Dwci_SettinglEraseAll(void);
void Write(unsigned int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SettinglConvAddress(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
int Ascii2hex(unsigned int param_1);
void Dwci_SndlInit(void);
void Dwci_SndlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SndlPlay(undefined4 param_1);
void Dwci_SndlSetVolume(undefined4 param_1);
void Dwci_SndlSetPitch(undefined4 param_1,undefined4 param_2);
void Dwci_SndlStop(void);
void Dwci_SteplBegin(int param_1);
void TaskBegin0(undefined4 param_1);
void TaskBegin1(undefined4 param_1);
void TaskBegin2(undefined4 param_1);
void TaskBegin3(undefined4 param_1);
void TaskBegin4(undefined4 param_1);
void Dwci_SteplEnd(void);
void Dwci_SteplChange(int param_1);
bool Dwci_SteplGet(void);
void TaskEnd0(undefined4 param_1);
void TaskEnd1(undefined4 param_1);
void TaskEnd2(undefined4 param_1);
void TaskEnd3(undefined4 param_1);
void TaskEnd4(undefined4 param_1);
bool Dwci_SteplIsEnd(void);
void Dwci_SteplChangeScr(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void TaskChange(undefined4 param_1);
undefined4 Dwci_UsbaplBegin(undefined4 param_1);
bool StartScan(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_UsbaplEnd(void);
void Dwci_UsbaplSetCallback(undefined4 param_1);
void CbWm(int16_t *param_1);
void ScanFirst(int param_1);
void ScanWait(int param_1);
void TaskFirst(undefined4 param_1);
void Dwci_WinlInitEx(undefined4 param_1,int param_2,int param_3,undefined4 param_4,undefined4 param_5);
void Dwci_WinlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int Dwci_WinlGet(void);
bool Dwci_WinlIsInit(void);
void TaskV(undefined4 param_1);
void TaskMove(undefined4 param_1);
void TaskMain(void);
void TaskMain1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Disp(unsigned int param_1);
void DispCell(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void PushButton(int param_1);
void TaskEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void TaskEnd1(undefined4 param_1);
void TaskEnd2(undefined4 param_1);
void TaskEnd3(undefined4 param_1);
void Dwci_Mov_Mbp_MemInit(int param_1);
void Dwci_Mov_Mbp_Start(undefined4 param_1,undefined4 param_2);
undefined4 Dwci_Mov_Mbp_RegistFile(int *param_1);
void Dwci_Mov_Mbp_AcceptChild(unsigned int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_Mov_Mbp_KickChild(unsigned int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_Mov_Mbp_StartDownload(unsigned int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_Mov_Mbp_StartDownloadAll(void);
undefined4 Dwci_Mov_Mbp_IsBootableAll(void);
void Dwci_Mov_Mbp_StartRebootAll(void);
void Dwci_Mov_Mbp_Cancel(void);
void Dwci_Mov_Mbp_ChangeState(undefined2 param_1);
undefined2 Dwci_Mov_Mbp_GetState(void);
undefined2 Dwci_Mov_Mbp_GetChildBmp(int param_1);
undefined4 Dwci_Mov_Mbp_GetChildState(unsigned int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int Dwci_Mov_Mbp_GetChildInfo(unsigned int param_1);
undefined2 Dwci_Mov_Mbp_GetPlayerNo(char *param_1);
void Dwci_Mov_WH_MemInit(int param_1);
void Dwci_Mov_WH_ChangeSysState(undefined4 param_1);
void Dwci_Mov_WH_SetError(undefined4 param_1);
undefined4 Dwci_Mov_WH_StateInSetParentParam(void);
void Dwci_Mov_WH_StateOutSetParentParam(int param_1);
undefined4 Dwci_Mov_WH_StateInSetParentWepKey(void);
void Dwci_Mov_WH_StateOutSetParentWepKey(int param_1);
undefined4 Dwci_Mov_WH_StateInStartParent(void);
void Dwci_Mov_WH_StateOutStartParent(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_Mov_WH_StateInStartParentMP(void);
void Dwci_Mov_WH_StateOutStartParentMP(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_Mov_WH_StateInStartParentKeyShare(void);
undefined4 Dwci_Mov_WH_StateInEndParentKeyShare(void);
undefined4 Dwci_Mov_WH_StateInEndChildMP(void);
void Dwci_Mov_WH_StateOutEndParentMP(int param_1);
undefined4 Dwci_Mov_WH_StateInEndParent(void);
undefined4 Dwci_Mov_WH_StateInEndChildKeyShare(void);
undefined4 Dwci_Mov_WH_StateInEndChildMP(void);
void Dwci_Mov_WH_StateOutEndChildMP(int param_1);
undefined4 Dwci_Mov_WH_StateInEndChild(void);
undefined4 Dwci_Mov_WH_StateInReset(void);
void Dwci_Mov_WH_StateOutReset(int param_1);
void Dwci_Mov_WH_StateOutEnd(int param_1);
void Dwci_Mov_WH_SetGgid(undefined4 param_1);
undefined2 Dwci_Mov_WH_GetBitmap(void);
undefined4 Dwci_Mov_WH_GetSystemState(void);
undefined4 Dwci_Mov_WH_StartMeasureChannel(void);
undefined2 Dwci_Mov_WH_StateInMeasureChannel(unsigned int param_1);
void Dwci_Mov_WH_StateOutMeasureChannel(int param_1);
void WHi_MeasureChannel(undefined4 param_1,undefined4 param_2);
undefined2 Dwci_Mov_WH_GetMeasureChannel(void);
int SelectChannel(unsigned int param_1);
bool Dwci_Mov_WH_Initialize(void);
undefined4 Dwci_Mov_WH_StateInInitialize(void);
void Dwci_Mov_WH_StateOutInitialize(int param_1);
undefined4 Dwci_Mov_WH_ParentConnect(int param_1,undefined2 param_2,undefined2 param_3);
void Dwci_Mov_WH_GetSharedDataAdr(undefined4 param_1);
undefined4 Dwci_Mov_WH_StepDS(undefined4 param_1);
void Dwci_Mov_WH_Reset(void);
void Dwci_Mov_WH_Finalize(void);
undefined4 Dwci_Mov_WH_End(void);
void Dwci_MovInit(int param_1,undefined4 *param_2);
undefined4 Dwci_MovFinalize(void);
void Dwci_MovPrepare(void);
undefined4 Dwci_MovStartAdmitChild(void);
undefined4 Dwci_MovStartDownloadandBootChild(void);
void Dwci_MovFramework(void);
void Dwci_MovGetStatus(undefined1 *param_1,undefined4 param_2);
void Dwci_MovSearchChannel(void);
void Dwci_MovStartWaitChild(void);
void Dwci_Mov_WaitandDownloadandBoot_Child(void);
void Dwci_Mov_ReadyMovUserID(void);
void Dwci_Mov_MovUserID(void);
void Dwci_Mov_EraseFlashData(void);
void Dwci_MovEnd(void);
undefined4 JudgeConnectableChild(int param_1);
void Parent_InitDataShare(void);
void Parent_StepDataShare(undefined2 param_1,undefined2 param_2,undefined4 *param_3);
void Parent_data_receive_progress(void);
undefined2 Parent_get_child_data_kind(void);
void Dwci_ArclInit(void);
void Dwci_ArclEnd(void);
undefined4 UserProc(undefined4 param_1,int param_2);
undefined4 CbRead(struct fs_archive *param_1,undefined4 param_2,int param_3,undefined4 param_4);
unsigned int * Dwci_ArclReadEx(char *param_1,unsigned int *param_2,int param_3);
void Dwci_ArclRelease(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
bool CmpBack(char *param_1,char *param_2,int param_3,undefined4 param_4);
void Dwci_CelllInit(void);
void Dwci_CelllEnd(void);
int Dwci_CelllForm(int param_1,int param_2,int param_3,undefined4 param_4);
void Dwci_CelllDelete(unsigned int param_1);
void Dwci_CelllSetEffect(int param_1,int param_2,unsigned int param_3,int param_4);
void Dwci_CelllSetPalette(int param_1,int param_2,int param_3,int param_4);
void Dwci_CelllSetPosition(int param_1,int param_2,int param_3,unsigned int param_4);
void Dwci_CelllSetPriority(int param_1,int param_2,int param_3);
void Dwci_CelllGetPosition(int param_1,int param_2,unsigned int *param_3,unsigned int *param_4);
void Dwci_CeinlRead(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_CeinlRelease(int param_1);
void Dwci_CeinlSet(int param_1,int param_2,int param_3);
undefined4 Dwci_CeinlSetExObj(undefined4 param_1,undefined4 param_2);
undefined4 Dwci_CeinlSetExCell(int param_1,int param_2);
void Dwci_QuelForm(int param_1);
void Dwci_QuelFormEx(int param_1,int param_2,int param_3);
void Dwci_QuelDelete(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_QuelPushBack(uint16_t *param_1,undefined4 param_2);
undefined4 Dwci_QuelPopBack(uint16_t *param_1);
void Dwci_EfflInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined1 Dwci_EfflCheck(int param_1);
undefined4 Dwci_EfflFade(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
void TaskFade(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_EfflWait(undefined2 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void TaskWait(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
void Dwci_FntlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_FntlEnd(void);
int Dwci_FntlFormEx(int param_1,int param_2,int param_3,undefined4 param_4,undefined4 *param_5,int param_6);
void Dwci_FntlDelete(int param_1);
int Dwci_FntlFormBgEx(int param_1,int param_2);
void TaskLoad(undefined4 param_1,char *param_2);
void Dwci_FntlDeleteBg(int param_1);
void Dwci_FntlDeleteBgLcd(int param_1);
void Dwci_FntlDraw(int param_1);
void Dwci_FntlDrawCharEx(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,undefined2 param_5,int param_6);
void Dwci_FntlDrawStringEx(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4,int param_5,uint16_t *param_6,int param_7);
void Dwci_FntlDrawRect(int param_1);
void Dwci_FntlClear(int param_1);
void Dwci_FntlDisp(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5);
void Dwci_FntlRenewBg(int param_1);
void Dwci_InputRect(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,undefined2 *param_5);
void Dwci_Coord2Rect(int16_t *param_1,int16_t *param_2,int16_t *param_3);
void Dwci_GXlVisible(int param_1,unsigned int param_2);
void Dwci_GXlInvisible(int param_1,unsigned int param_2);
void Dwci_GXlSetWndPosition(int param_1,int param_2,int16_t *param_3);
void Dwci_GXlSetWndPlane(int param_1,undefined4 param_2,int param_3,int param_4);
void Dwci_HeaplInit(int8_t *param_1);
void Dwci_HeaplEnd(void);
void * Dwci_HeaplAlloc(undefined4 param_1,undefined4 param_2);
int8_t * Dwci_HeaplAllocEx(unsigned int param_1);
void Dwci_HeaplFree_(int *param_1);
void Dwci_IptlInit(void);
void Dwci_IptlEnd(void);
void Dwci_IptlRead(void);
void readKey(void);
void readTouch(void);
void Dwci_IptlCheckFold(void);
void Dwci_ItrlIntr(void);
void Dwci_ItrlEnd(void);
void Dwci_LstlForm(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_LstlDelete(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_LstlErase(int *param_1);
void Dwci_LstlInsert(int *param_1,int *param_2);
void Dwci_ObjlInit(void);
void TaskTransfer(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_ObjlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_ObjlFormGx(int param_1);
void Dwci_ObjlDelete(unsigned int *param_1);
int Dwci_ObjlGetOam(int param_1,int param_2);
void Dwci_OvrlInit(void);
int Dwci_OvrlAlloc(int param_1,int param_2,int param_3,unsigned int *param_4);
void Dwci_OvrlFree(unsigned int param_1);
int Dwci_StrlNLen(int param_1,int param_2);
void Dwci_ClearVram(void);
void ClearVram(void);
void Dwci_SetLedWireless(void);
void Dwci_TsklInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_TsklEnd(void);
void Dwci_TsklAct(int param_1);
void Dwci_TsklForm(void);
int FormTask(int param_1,undefined4 param_2,undefined4 param_3,unsigned int param_4,undefined1 param_5);
void Dwci_TsklDelete(int param_1,undefined4 param_2);
void DeleteTcb(int param_1,int param_2);
void Dwci_TsklOperate(int param_1,undefined1 param_2);
undefined1 Dwc_Init(undefined4 param_1);
undefined4 Nhttp_Startup(void* *param_1,void* *param_2,undefined4 param_3);
void Nhttpi_CleanupThreadProc(void* *param_1);
undefined4 AddHdrList(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int * Nhttpi_getHdrFromList(int *param_1);
int IncAscii(char param_1);
undefined4 CheckTagPost(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Nhttp_AddHeaderField(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int Nhttp_AddPostDataAscii(int *param_1,undefined4 param_2,undefined4 param_3);
bool Nhttp_SetCaChain(int *param_1,int param_2,int param_3);
int Nhttpi_setReqQueue(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int Nhttpi_findReqQueue(int param_1);
undefined4 Nhttpi_freeReqQueue(void);
void Nhttpi_allFreeReqQueue(void);
undefined4 Nhttpi_initLockReqList(void);
void ret_0215e1f4(void);
undefined4 Nhttpi_createCommThread(undefined4 param_1,int param_2);
void Nhttpi_destroyCommThread(void);
void Nhttpi_kickCommThread(void);
void SetupGetcharFromHdrRecvBuf(int param_1,unsigned int param_2,undefined4 *param_3,unsigned int *param_4);
int GetcharFromHdrRecvBuf(int param_1,int *param_2,int *param_3);
int Nhttpi_findNextLineHdrRecvBuf(undefined4 param_1,int param_2,int param_3,int *param_4);
int Nhttpi_skipSpaceHdrRecvBuf(undefined4 param_1,int param_2,int param_3);
int Nhttpi_compareTokenN_HdrRecvBuf(undefined4 param_1,int param_2,int param_3,char *param_4,int param_5);
undefined4 Nhttpi_loadFromHdrRecvBuf(int *param_1,int param_2,int param_3,int param_4);
bool Nhttpi_isRecvBufFull(int param_1,unsigned int param_2);
void Nhttpi_RecvBuf(int param_1,undefined4 param_2,int param_3,undefined4 param_4);
undefined4 Nhttpi_RecvBufN(int param_1,undefined4 param_2,int param_3,int param_4);
int Nhttp_CreateRequest(int param_1,unsigned int param_2,undefined4 param_3,int param_4,undefined4 param_5,undefined4 param_6);
void Nhttp_DestroyRequest(int param_1);
void DeleteStrList(int *param_1);
undefined4 Nhttpi_destroyRequestObject(int param_1);
int Nhttp_SendRequestAsync(int *param_1);
void Nhttpi_cancelAllRequests(void);
unsigned int Nhttpi_resolveHostname(int param_1,undefined4 param_2,undefined4 param_3,unsigned int param_4);
void Nhttp_DestroyResponse(int param_1);
int Nhttpi_getHeaderValue(int *param_1,undefined4 param_2,int *param_3);
int Nhttp_GetHeaderField(int param_1,undefined4 param_2,undefined4 *param_3,undefined4 param_4);
undefined4 Nhttp_GetBodyAll(int param_1,undefined4 *param_2);
void Nhttpi_SetSsLseed(void);
int Nhttpi_SocOpen(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Nhttpi_SocCloseWait(undefined4 param_1,int param_2);
undefined4 Nhttpi_SocConnect(int param_1,int param_2,struct socklen_t param_3,unsigned int param_4);
struct ssize_t Nhttpi_SocRecv(int param_1,int param_2,void *param_3,struct size_t param_4,int param_5);
struct ssize_t Nhttpi_SocSend(int param_1,int param_2,void *param_3,struct size_t param_4,int param_5);
void Nhttpi_SocCancel(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
int Nhttpi_strnicmp(char *param_1,char *param_2,int param_3);
void Nhttpi_memclr(int8_t *param_1,unsigned int param_2);
void Nhttpi_memcpy(undefined4 *param_1,undefined4 *param_2,unsigned int param_3);
undefined4 Nhttp_GetProgress(undefined4 *param_1,undefined4 *param_2);
int SaveBuf(int param_1,undefined4 param_2,int *param_3,int param_4,int param_5);
int SkipLineBuf(undefined4 param_1,undefined4 param_2);
void FreeSslConnection(int param_1);
void PutSocketToCloseQue(undefined4 param_1,int *param_2);
void ClearCloseQue(void);
int Nhttpi_getUrlEncodedSize(char *param_1);
undefined4 Nhttpi_encodeUrlChar(undefined1 *param_1,unsigned int param_2);
int Nhttpi_strToHex(char *param_1,int param_2);
int Nhttpi_strToInt(int param_1,int param_2);
int Nhttpi_intToStr(int param_1,unsigned int param_2);
undefined4 Nhttpi_compareToken(char *param_1,char *param_2);
int Nhttpi_strtonum(char *param_1,int param_2);
undefined4 Nhttpi_memfind(int param_1,int param_2,char *param_3,int param_4);
void Dwci_Ndi_freeAttr(void);
undefined4 SetAttr(int param_1,char *param_2);
undefined4 Dwci_NdSetAttr(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int GetNchar(char *param_1,char *param_2,int param_3);
int DecodeChar(unsigned int param_1);
int Dwci_Ndi_getEncodeLenBase64(int param_1);
int Dwci_Ndi_encodeBase64(char *param_1,int param_2,int param_3,unsigned int param_4);
int StrAlloc(undefined4 param_1);
undefined4 Dwci_NdStartup(undefined4 param_1,void* *param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5,undefined4 param_6,undefined4 param_7);
void NhttpCleanupCallback(void);
void Dwci_NdCleanupAsync(undefined4 param_1);
undefined4 Dwci_Ndi_getDSdesc(undefined4 param_1,undefined4 param_2);
void Dwci_Ndi_getUserAgent(undefined4 param_1);
void req_callback(int param_1,undefined4 param_2,int param_3,undefined4 param_4);
void FreeHttp(undefined4 param_1,undefined4 param_2);
undefined4 SetupHttp(int *param_1,int *param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5);
undefined4 runHttp(int *param_1,undefined4 param_2);
bool Dwci_NdGetFileListNumAsync(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_NdGetFileListAsync(undefined4 param_1,undefined4 param_2,int param_3);
undefined4 Dwci_NdGetFileAsync(int param_1,undefined4 param_2,unsigned int param_3,undefined4 param_4);
undefined4 Nhttp_GetProgress(undefined4 *param_1,undefined4 *param_2);
bool Dwci_Ndi_response_count(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
bool Dwci_Ndi_response_contents(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_Ndi_initLockGlobal(void);
void ret_021626e0(void);
undefined4 Dwci_Ndi_initHttpCallback(void);
void ret_02162734(void);
bool Dwci_Ndi_prepareHttpCallback(undefined4 param_1,int param_2);
void Dwci_Ndi_unprepareHttpCallback(undefined4 param_1,int param_2);
void Dwci_Ndi_kickThread(undefined4 param_1);
void Dwci_Ndi_getMacAddress(undefined4 param_1);
void Dwci_Ndi_memclr(int8_t *param_1,unsigned int param_2);
void Dwci_Ndi_memcpy(undefined4 *param_1,undefined4 *param_2,unsigned int param_3);
int Nhttpi_strToInt(int param_1,int param_2);
int Nhttpi_intToStr(int param_1,unsigned int param_2);
int Dwci_Ndi_hexToStrFigure(int param_1,unsigned int param_2,int param_3);

#endif
