#ifndef HEADERS_FUNCTIONS_OVERLAY11_H_
#define HEADERS_FUNCTIONS_OVERLAY11_H_

struct c_ranger_net_scene * CRangerNetSceneConstructor(struct c_ranger_net_scene *this,struct megastruct *param_2);
void CRangerNetSceneInit(struct c_ranger_net_scene *param_1);
void ret_0211d860(void);
struct c_ranger_net_agb_scene * CRangerNetAGBSceneConstructor(struct c_ranger_net_agb_scene *this);
void ret_0211df48(void);
void ret_0211df4c(void);
void ret_0211df50(void);
void ret_0211df58(void);
void ret_0211df5c(void);
void ret_0211df60(void);
struct ov_11_unk_struct_0x730 *Ov110x730Constructor(struct ov_11_unk_struct_0x730 *this,struct megastruct * megastruct_ptr,int param_3);
void Ov110x730InitPrimary(struct ov_11_unk_struct_0x730 *this);
void Ov110x730InitSecondaryVeneer(struct ov_11_unk_struct_0x730 *this);
void Ov110x730InitSecondary(struct ov_11_unk_struct_0x730 *param_1);
void MaybeFreeRangerNetScene(struct ov_11_unk_struct_0x730 *param_1);
void ret_021245a4(void);
int Return0x2700(void);
void ret_02126964(void);
void ret_02126968(void);
void ret_0212697c(void);
void ret_02126980(void);
void ret_02126984(void);
struct ov_11_unk_struct_0x3ec *Ov110x3ecConstructor(struct ov_11_unk_struct_0x3ec *this,struct megastruct * megastruct_ptr_ptr,struct ov_11_unk_struct_0x730 *parent);
int MaybeInitRsaKeyFileData(int param_1,char *param_2,undefined4 param_3,undefined4 param_4);
void ret_0212d978(void);
struct ov_11_unk_struct_0x198 *Ov110x198Constructor(struct ov_11_unk_struct_0x198 *this,struct ov_11_unk_struct_0x730 *parent);
struct ov_11_unk_struct_0x18 * Ov110x18Constructor(struct ov_11_unk_struct_0x18 *param_1,struct megastruct * megastruct_ptr);
struct ov_11_unk_struct_0x4e4 *Ov110x4e4Constructor(struct ov_11_unk_struct_0x4e4 *param_1,struct megastruct * megastruct_ptr_ptr,struct ov_11_unk_struct_0x18 *param_3,struct ov_11_unk_struct_0x730 *param_4);
struct ov_11_unk_struct_2 * Overlay11EntryPoint2(struct ov_11_unk_struct_2 *param_1);
void ret_0213201c(void);
void ret_02132020(void);
undefined4 Dwc_AC_Process(void);
void Dwc_AC_GetStatus(void);
undefined1 Dwc_AC_GetApType(void);
undefined4 Dwc_AC_Destroy(void);
void Dwci_AC_InsertApInfo(int param_1,undefined4 param_2);
void Dwci_AC_Alloc(unsigned int param_1,undefined4 param_2);
struct unk_wifi_struct_0x18 * Dwci_AC_GetMemPtr(unsigned int param_1);
void Dwci_AC_SetPhase(unsigned int param_1);
undefined1 MaybeGetWfcInitCase(void);
void Dwci_AC_SetError(undefined4 param_1);
undefined4 Dwci_AC_GetError(void);
unsigned int Dwci_ConvConnectAPType(unsigned int param_1);
void Free_Disused(void);
undefined4 CheckDuplicate(void);
undefined4 Dwci_AC_CheckNintendoSSID(int param_1);
unsigned int CompareList(int param_1,int param_2,int param_3);
unsigned int CompareListDiff(int param_1,int param_2);
int AddList(undefined1 param_1,int param_2,undefined4 param_3,int param_4);
void SetDataListTail(undefined1 param_1,int param_2,int8_t param_3,int param_4);
void UpDateList(int param_1,int param_2,int8_t param_3,int param_4);
void SortList(int param_1,int param_2);
void Dwci_AC_CallBackWCM(int16_t *param_1);
int Dwci_AC_ConnectAP(void);
undefined4 ConnectStart(int param_1);
undefined4 ConnectAP(int param_1);
unsigned int GetConnectType(int param_1);
undefined4 GetPowerMode(int param_1);
undefined4 GetAuthMode(int param_1);
undefined4 Dwci_AC_CloseNetwork(int8_t *param_1);
undefined4 DisConnectAP(void);
bool CloseSocket(void);
undefined4 Dwci_AC_Error(void);
void Dwci_AC_GetResult(void);
undefined4 GetProgramaError(undefined4 param_1);
undefined4 GetNotFoundAP(int param_1);
undefined1 Dwci_AC_MakeSearchList(int param_1);
undefined4 Dwci_AC_CheckFreespot(int param_1);
unsigned int MakeAroundList(int param_1);
unsigned int MakeStealthList(int param_1);
char MakeUserList(int param_1);
char MakeDifferChannelList(int param_1);
unsigned int CheckDifferChannelStart(int param_1);
int8_t Dwci_AC_ConnectRetryAP(void);
int Dwci_AC_SearchAP(void);
void Dwci_AC_SetStealthChannel(unsigned int param_1);
int Dwci_AC_GetStealthChannel(unsigned int param_1);
void Dwci_AC_SearchReStart(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 SearchStart(int param_1);
undefined4 SearchAround(int param_1);
undefined4 SearchAround2ndLap(int param_1);
undefined4 SearchDifferChannel(int param_1);
undefined4 SearchStealth(int param_1);
int NextSearchCheck(int param_1,int param_2);
int SearchEndCheck(unsigned int param_1,int param_2);
undefined4 CheckStartStealthSearch(int param_1);
void ScanStart(undefined4 param_1,undefined4 param_2,int param_3,unsigned int param_4);
undefined4 Dwci_AC_Start(void);
int Dwci_AC_ConnectTest(void);
undefined4 ConnectTestStart(undefined4 param_1);
undefined4 GetIPAddress(int param_1);
undefined4 ConnectTestCreate(void);
undefined4 ConnectTestProcess(int param_1);
undefined4 ConnectTestEnd(int param_1);
undefined4 ConnectTestRetry(void);
void MakeSOCConfig(undefined4 *param_1,int param_2,undefined4 *param_3);
unsigned int ConvAddress(int8_t *param_1);
unsigned int ConvNetMask(int param_1);
void CheckSetDNS(int param_1);
bool Dwci_AC_CheckNintendoShopAP(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_AC_GetNintendoShopWepKey(undefined4 param_1,undefined4 param_2);
void Dwci_AC_GetPostalCode(undefined4 param_1,undefined4 *param_2);
bool Dwci_AC_CheckNintendoUsbAP(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void decodeSSID(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
void makeShopWepKey(undefined4 param_1,undefined4 *param_2);
void makeUsbWepKey(int param_1,undefined4 *param_2);
int codetovalue(unsigned int param_1);
unsigned int db64(int param_1,int param_2,unsigned int param_3,unsigned int param_4);
void Dwc_Auth_SetCustomNas(char *param_1);
int Dwc_Auth_Create(undefined4 *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_Auth_StartThread(void);
void Dwc_Auth_Abort(undefined4 param_1,int param_2);
void Dwc_Auth_Destroy(void);
undefined4 Dwc_Auth_GetError(undefined4 param_1,int param_2);
void Dwc_Auth_GetResult(int *param_1);
undefined4 Dwci_Auth_Start(int param_1);
void Dwci_Auth_Thread(void);
undefined4 Dwci_Auth_ParseHttp(void);
undefined4 Dwci_Auth_FillResult(void);
undefined4 Dwci_Auth_Prepare_FirstPost(undefined4 param_1,char *param_2,undefined4 param_3,undefined4 param_4);
void Dwci_Auth_SetError(undefined4 param_1);
void Dwc_Auth_GetCalInfoFromNVRAM(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
bool Dwc_Auth_SetCalInfoToHttp(undefined4 param_1,char *param_2,int param_3);
undefined4 Dwc_Http_Create(int8_t *param_1,undefined4 *param_2);
undefined4 Dwc_Http_FinishHeader(int param_1);
void Dwc_Http_StartThread(int param_1,undefined4 param_2);
void Dwc_Http_Abort(int param_1,int param_2);
undefined4 Dwci_Http_Yield(int param_1,int param_2);
void Dwci_Http_InitCpsSocket(int param_1);
void Dwci_Http_Resolve(int param_1);
undefined4 Dwci_Http_CheckHeaderReceived(int param_1);
void Dwci_Http_Thread(int param_1);
void Dwc_Http_Destroy(int8_t *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_Http_WriteBasicHeader(int param_1);
undefined4 Dwc_Http_Add_HeaderItem(int param_1,char *param_2,char *param_3);
undefined4 Dwc_Http_Add_PostBase64Item(int param_1,char *param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwc_Http_Add_Body(int param_1,char *param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_Http_AllocBuffer(int param_1,int *param_2,int param_3,undefined4 param_4);
void Dwci_Http_FreeBuffer(int param_1,int *param_2);
undefined4 Dwci_Http_ReallocBuffer(int param_1,int *param_2,int param_3,undefined4 param_4);
undefined4 Dwci_Http_SetHostinfo(int param_1,char *param_2);
undefined4 Dwci_Http_AddResult(int param_1,int *param_2,char *param_3,char *param_4);
undefined4 Dwc_Http_ParseResult(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwc_Http_GetResult(int param_1,char *param_2);
void Dwc_Http_GetBase64DecodedResult(undefined4 param_1,undefined4 param_2,int param_3,unsigned int param_4);
undefined4 Dwc_Http_GetRawResult(undefined4 param_1,undefined4 param_2,char *param_3,int param_4);
void Dwci_Http_DestroyResult(int param_1,int param_2,int param_3);
undefined4 Dwc_Netcheck_Create(undefined4 *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwc_Netcheck_Destroy(void);
void Dwc_Netcheck_Abort(void);
undefined4 Dwc_Netcheck_GetError(undefined4 param_1,int param_2);
undefined4 Dwc_Netcheck_GetReturnCode(void);
void Dwci_Netcheck_StartThread(void);
void Dwci_Netcheck_SetError(undefined4 param_1);
undefined4 Dwc_Auth_SetNasTimeDiff(char *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwc_Svl_Init(void* *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwc_Svl_Cleanup(void);
undefined4 Dwc_Svl_GetTokenAsync(undefined4 param_1,int8_t *param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwc_Svl_Process(void);
undefined4 Dwci_Svl_ParseHttp(void);
unsigned int Dwc_Auth_Base64Encode(undefined4 *param_1,unsigned int param_2,int param_3,unsigned int param_4);
int8_t * Dwc_Auth_Base64Decode(int param_1,unsigned int param_2,int8_t *param_3,int8_t *param_4);
void Dwci_BM_GetWiFiInfo(undefined4 *param_1);
bool Dwci_BM_SetWiFiInfo(undefined4 param_1,int param_2);
undefined4 Dwci_BACKUPlInit(uint16_t *param_1);
bool Dwci_BACKUPlRead(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
bool Dwci_BACKUPlWritePage(int param_1,int param_2,undefined4 param_3);
bool Dwci_BACKUPlWriteAll(int param_1);
void Dwci_BACKUPlSetWiFi(undefined4 *param_1);
char Dwci_BACKUPlConvMaskCidr(int param_1);
void Dwci_BACKUPlConvMaskAddr(unsigned int param_1,int param_2);
undefined4 Dwc_BACKUPlCheckSsid(int param_1);
bool Dwc_BACKUPlCheckIp(undefined4 *param_1,undefined4 *param_2,undefined4 param_3,undefined4 param_4);
bool Dwc_BACKUPlCheckAddress(int8_t *param_1);
bool verify(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
uint16_t Callback_NVRAM(undefined4 param_1,uint16_t param_2,int param_3);
undefined * Dwci_BACKUPlConvWifiInfo(undefined4 *param_1);
undefined4 Dwc_BM_Init(int8_t *param_1);
undefined4 checkAp(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 init(int16_t *param_1);
void initPage(int param_1,int param_2);
unsigned long long Dwci_Util_WiFiId_scrambleUid(unsigned int param_1,unsigned int param_2,unsigned int param_3,unsigned int param_4);
undefined4 Dwci_AUTH_GetNewWiFiInfo(undefined4 *param_1);
bool Dwci_AUTH_MakeWiFiID(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
bool Dwci_AUTH_UpDateWiFiID(undefined4 *param_1,undefined4 param_2);
undefined4 Dwci_AUTH_RemakeWiFiID(int param_1);
bool Dwc_Auth_CheckWiFiIDNeedCreate(void);
undefined4 Dwc_GetLastError(undefined4 *param_1);
undefined4 Dwc_GetLastErrorEx(undefined4 *param_1,undefined4 *param_2);
bool Dwci_IsError(void);
void Dwci_SetError(int param_1,undefined4 param_2);
void Dwc_InitInetEx(struct DWCInetControl *inetCntl,uint16_t dmaNo,uint16_t powerMode,uint16_t ssl_priority);
void Dwc_InitInet(struct DWCInetControl *inetCntl);
void Dwc_SetAuthServer(int param_1);
bool Dwc_CheckInet(void);
void Dwc_ProcessInet(void);
undefined4 Dwc_GetInetStatus(void);
void Dwc_CleanupInet(void);
undefined4 Dwc_CleanupInetAsync(void);
undefined4 Dwci_CheckDisconnected(void);
undefined4 Dwc_UpdateConnection(void);
undefined4 Dwc_SVLGetTokenAsync(char *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int Dwc_SVLProcess(void);
undefined4 Dwc_NASLoginAsync(void);
undefined4 Dwc_NASLoginProcess(void);
void Dwci_NdAlloc(int param_1,undefined4 param_2);
void Dwci_NdFree(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_NdCallback(undefined4 param_1,int param_2,int param_3);
void Dwci_NdCleanupCallback(void);
void Dwci_SVLTokenWaitThread(void);
undefined4 Dwc_NdInitAsync(undefined4 param_1,char *param_2,char *param_3);
undefined4 Dwc_NdCleanupAsync(undefined4 param_1);
undefined4 Dwc_NdSetAttr(undefined4 param_1,undefined4 param_2,undefined4 param_3);
undefined4 Dwc_NdGetFileListNumAsync(undefined4 param_1);
undefined4 Dwc_NdGetFileListAsync(int8_t *param_1,undefined4 param_2,int param_3);
undefined4 Dwc_NdGetFileAsync(undefined4 param_1,undefined4 param_2,undefined4 param_3);
undefined4 Dwc_NdGetProgress(undefined4 param_1,undefined4 param_2);
void Aoss_MALLOC(void);
void Aoss_FREE(void);
undefined4 Aossi_Init(int param_1);
void aoss_release(void);
void aoss_data_init(uint16_t *param_1);
undefined4 Aoss_seq_data_copy(uint16_t *param_1);
undefined4 aoss_check_str(int8_t *param_1,int param_2);
undefined4 checkAP(unsigned int *param_1);
undefined4 Aoss_set_APInfo(undefined4 *param_1);
void MakeSendSeqID(int param_1,int param_2,undefined4 param_3);
undefined4 Aoss_StatusExclusion(int param_1);
undefined4 RecvMessage(undefined4 param_1,int param_2,int *param_3,undefined4 param_4);
int AstsSetInitRes(int param_1,int param_2,int *param_3,undefined4 param_4);
int AstsSetSecureRes(int param_1,int param_2,int *param_3,int param_4);
int AstsRestartRes(int param_1,int param_2,int *param_3,int param_4);
int DecodePacket(int param_1);
undefined4 CheckSeqID(int param_1,undefined4 param_2);
undefined4 CheckRecvSeqID(int param_1,int param_2);
undefined4 GetProductInfo(undefined1 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
int aoss_get_bin(int param_1,int param_2);
undefined4 GetWEPData(int param_1,int param_2);
undefined4 GetWPAData(int param_1,int param_2);
undefined4 GetBssidData(int param_1,undefined4 param_2);
int GetSecurityData(int param_1,char *param_2,int param_3,int param_4,int param_5);
bool GetSecurityType(unsigned int param_1);
undefined4 SendMessage(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 AstsSetInitReq(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 AstsSetSecureReq(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
undefined4 AstsRestartReq(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
int SetStaData(undefined1 *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void PacketDataSet(int param_1,undefined2 *param_2,undefined4 param_3,int16_t *param_4,undefined2 *param_5,undefined4 param_6);
void SetPacketHeader(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,undefined1 param_5,undefined1 param_6,undefined4 param_7);
void SendPacketUDP(undefined4 param_1,undefined4 param_2,int param_3,undefined4 param_4);
undefined4 EncodeRC4(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined1 *param_4,undefined4 param_5,undefined4 param_6,int param_7);
undefined4 DecodeRC4(undefined4 param_1,undefined4 param_2,undefined4 param_3,int param_4,undefined4 param_5,undefined4 param_6,int param_7);
void RC4encrypt(undefined4 param_1,int param_2,int param_3,unsigned int param_4);
int8_t crc(undefined4 param_1,undefined4 param_2);
unsigned int update_crc(unsigned int param_1,int param_2,int param_3,int param_4,int param_5);
void make_crc_table(undefined4 param_1,unsigned int *param_2);
undefined4 CryptSeqNo(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
void AddKey(int param_1,int param_2,int param_3);
void Rotate(int param_1,int param_2,int param_3,undefined4 param_4);
int Aoss_Memcmp(int8_t *param_1,int8_t *param_2,int param_3);
void Aoss_Memcpy(undefined4 *param_1,undefined4 *param_2,unsigned int param_3);
void Aoss_Memset(int8_t *param_1,unsigned int param_2,unsigned int param_3);
void ret_0213e00c(void);
int SocketVeneer(int __domain,int __type,int __protocol);
unsigned int Aoss_Htonl(unsigned int param_1);
unsigned int Aoss_Htons(unsigned int param_1);
unsigned int Aoss_Ntohl(unsigned int param_1);
unsigned int Aoss_Ntohs(unsigned int param_1);
int Aoss_Strlen(char *param_1);
undefined4 Aossi_Status(void);
uint16_t * GetFrameData(uint16_t *param_1,unsigned int *param_2,unsigned int *param_3);
uint16_t * GetElementData(int *param_1,uint16_t *param_2,unsigned int *param_3,unsigned int *param_4);
void GetFirstElement(uint16_t *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void SetSingleElement(int16_t *param_1);
undefined4 IsSearchCommand(undefined4 param_1,unsigned int *param_2);
void SetSearchRes(undefined4 param_1);
undefined4 AsciiToHex(int param_1,int param_2,int param_3);
void aeskw_xor64(int8_t *param_1,int8_t *param_2,int8_t *param_3);
undefined4 rijndaelKeySetupEnc(unsigned int *param_1,int8_t *param_2,int param_3);
int rijndaelKeySetupDec(unsigned int *param_1);
void rijndaelEncrypt(unsigned int *param_1,int param_2,int8_t *param_3,undefined1 *param_4);
void rijndaelDecrypt(unsigned int *param_1,int param_2,int8_t *param_3,undefined1 *param_4);
void MY_MD5Init(undefined4 *param_1);
void MY_MD5Update(int param_1,int param_2,unsigned int param_3,undefined4 param_4);
void MY_MD5Final(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
void MD5Transform(int *param_1,undefined4 param_2);
void Encode(int param_1,undefined4 *param_2,unsigned int param_3);
void Decode(undefined4 *param_1,int param_2,unsigned int param_3);
void MD5_memcpy(int param_1,int param_2,unsigned int param_3);
void MD5_memset(undefined1 *param_1,undefined1 param_2,unsigned int param_3);
void MD5Encode(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int PutHex(char *param_1,unsigned int param_2);
int PutMac(undefined1 *param_1,char *param_2);
undefined4 Atermi_ApConfigGetState(undefined4 *param_1);
void SendNotify(void);
void Dwci_ANIMElInitEx(int param_1);
void Dwci_ANIMElEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void taskAnime(void);
void Dwci_BTNlInit(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_BTNlEnd(void);
int Dwci_BTNlGet(void);
void Dwci_BTNlSet(undefined1 param_1);
void Dwci_BTNlSetForce(undefined1 param_1);
bool Dwci_BTNlIsEnd(void);
void Dwci_BTNlEnable(void);
void Dwci_BTNlDisable(void);
void disp(int param_1);
void taskStart(undefined4 param_1);
void taskStart1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void taskMain(void);
void taskEnd(undefined4 param_1);
void taskEnd1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void taskRelease(undefined4 param_1);
void Dwci_COMMENTlInit(void);
undefined4 Dwci_COMMENTlDispEx(undefined4 param_1,undefined4 param_2,undefined4 param_3);
undefined4 Dwci_COMMENTlDelete(void);
void Dwci_Char(char *param_1);
void Dwci_CMNlLoadResource(undefined4 param_1,void* *param_2,undefined4 param_3,undefined4 param_4);
void Dwci_CMNlStep(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_CMNlButton(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_CMNlMsgDraw(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_CMNlMsgNameDraw(undefined4 param_1,undefined4 param_2);
undefined4 Dwci_CMNlFontFlag(void);
void Dwci_FOCUSlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_FOCUSlEnd(void);
void Dwci_FOCUSlDisp(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_FOCUSlDisp4(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_FOCUSlDelete(void);
void Dwci_HLlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_HLlLoad(int param_1);
void Dwci_HLlLoadSet(void);
void Dwci_HLlLoadList(void);
void taskLoad(undefined4 param_1);
void Dwci_ICONlInit(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_ICONlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void taskRenew(void);
void Dwci_KBlInit(void);
void Dwci_KBlEnd(void);
undefined1 Dwci_KBlGet(void);
void Dwci_KBlSetErase(undefined1 param_1);
void Dwci_KBlSetInput(undefined1 param_1);
bool Dwci_KBlIsInit(void);
void taskStart0(undefined4 param_1);
void taskStart1(undefined4 param_1);
void taskStart2(undefined4 param_1);
void taskStart3(undefined4 param_1);
void taskStart4(undefined4 param_1);
void touchTriger(void);
void touchRelease(void);
void pushCaps(void);
void pushShift(void);
void touch(void);
void exchangeBack(int param_1);
void key(void);
void disp(int param_1,int param_2,unsigned int param_3,undefined4 param_4);
void changePage(int param_1);
void changeColor(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
void dispFocus(void);
void moveFocus(int param_1);
void taskEnd0(undefined4 param_1);
void taskEnd1(undefined4 param_1);
void taskEnd2(undefined4 param_1);
void taskEnd3(undefined4 param_1);
void taskEnd4(undefined4 param_1);
void taskEnd5(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_KB10lInit(void);
void Dwci_KB10lEnd(void);
undefined1 Dwci_KB10lGet(void);
void Dwci_KB10lSetErase(undefined1 param_1);
void Dwci_KB10lSetInput(undefined1 param_1);
void Dwci_KB10lSetShift(undefined1 param_1);
bool Dwci_KB10lIsInit(void);
void taskStart0(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void taskStart1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void taskStart2(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void taskStart3(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void taskStart4(undefined4 param_1);
void touchTriger(void);
void touchRelease(void);
void touch(void);
void exchangeBack(int param_1);
void key(void);
void disp(int param_1,unsigned int param_2);
void changeColor(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
void dispFocus(void);
void moveFocus(int param_1);
void taskEnd0(undefined4 param_1);
void taskEnd1(undefined4 param_1);
void taskEnd2(undefined4 param_1);
void taskEnd3(undefined4 param_1);
void taskEnd4(undefined4 param_1);
void taskEnd5(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwc_StartUtility(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 checkParam(int param_1,unsigned int param_2);
void initGame(void);
void initGraph(void);
void procEnd(void);
void Dwci_SetParam_(undefined4 param_1,undefined4 param_2);
void Dwci_GetParam_(undefined4 *param_1,undefined4 *param_2);
void Dwci_SetParam2_(undefined4 param_1,undefined4 param_2);
void Dwci_GetParam2_(undefined4 *param_1,undefined4 *param_2);
unsigned int Dwci_Entry(void);
bool Dwci_Flag(unsigned int param_1);
void Dwci_EndUtility(void);
char kDwci_Language(void);
void Dwci_MSGlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int * Dwci_MSGlRead(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_MSGlRelease(int param_1);
int Dwci_MSGlGet(int *param_1,unsigned int param_2);
void Dwci_MSGlGetEx(int *param_1,unsigned int param_2,int param_3,int16_t param_4);
void Dwci_MovlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_MovlEnd(void);
void taskEnd(undefined4 param_1);
bool Dwci_MovlIsEnd(void);
void Dwci_MovlChangeCallback(undefined4 param_1);
void Dwci_MovStartDownloadandBootChild(void);
int Dwci_MovlGetChild(void);
void taskFramework(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SceneEnd(void);
void endScene(void);
void Dwci_SceneInit(void);
void procFade(void);
void procWait(void);
void Dwci_SceneMenu(void);
void initGraphics(void);
void procInit(void);
void procInit1(void);
void input(void);
void ret_02147dbc(void);
void button(void);
void endScene1(void);
void endScene2(void);
void moveFocus(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void dispPushButton(void);
void Dwci_SceneOptErase(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void input(void);
void ret_021481a0(void);
void button(void);
void endScene1(void);
void endScene2(void);
void procConfirm(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void input(void);
void ret_02148518(void);
void button(void);
void endScene1(void);
void endScene2(void);
void Dwci_SceneOptInfo(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void drawInfo(void);
void procInit(void);
void procInit1(void);
void input(void);
void ret_02148958(void);
void button(void);
void endScene1(void);
void endScene2(void);
void Dwci_SceneOptMenu(void);
void initGraphics(void);
void procInit(void);
void procInit1(void);
void input(void);
void ret_02148e88(void);
void button(void);
void endScene1(void);
void endScene2(void);
void moveFocus(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void dispPush(void);
void Dwci_SceneOptMovComm(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void ret_021492a8(void);
void ret_021492ac(void);
void endScene(void);
void endScene1(void);
void cbMov(int param_1);
void initGraphics(void);
void procInit(void);
void procInit1(void);
void input(void);
void ret_02149538(void);
void button(void);
void endScene1(void);
void endScene2(void);
void Dwci_SceneOptMovComplete(void);
void initGraphics(void);
void procInit(void);
void procInit1(void);
void input(void);
void ret_02149758(void);
void button(void);
void Dwci_SceneOptMovConfirm1(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void input(void);
void ret_021499ec(void);
void button(void);
void endScene1(void);
void endScene2(void);
void Dwci_SceneOptMovDisconnect(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void ret_02149c8c(void);
void endScene(void);
void endScene1(void);
void Dwci_SceneOptMovFailure(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void procInit2(void);
void input(void);
void ret_02149f44(void);
void button(void);
void endScene1(void);
void endScene2(void);
void Dwci_SceneOptMovUser(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procScene(void);
void ret_0214a308(void);
void ret_0214a30c(void);
void endScene(void);
void endScene1(void);
void endScene2(void);
bool Dwci_IsFold(void);
void Dwci_SceneOptMovWait(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void input(void);
void ret_0214a660(void);
void button(void);
void endScene(void);
void endScene1(void);
void endScene2(void);
void cbMov(int param_1);
bool Dwci_IsFold(void);
void Dwci_SceneSetAossButton(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void procInit2(void);
void procScene(void);
void input(void);
void ret_0214aba8(void);
void button(void);
void endScene(void);
void endScene1(void);
void endScene2(void);
void procError(void);
void procWait(void);
void procCancel(void);
void Dwci_SceneSetAossComplete(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void ret_0214af68(void);
void endScene(void);
void endScene1(void);
void Dwci_SceneSetApList(void);
void initGraphics(void);
void initScrollBar(void);
void getCharName(void);
void procInit(void);
void procInit1(void);
void input(void);
void draw(void);
void button(void);
void endScene1(void);
void endScene2(void);
void drawApInfo(void);
void drawAp(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
void drapApObj(int param_1,int param_2);
void setOffset(void);
void taskUp(undefined4 param_1);
void taskDown(undefined4 param_1);
void taskVBlank(void);
void dispFocus(void);
void moveFocus(int param_1);
void scrollUp(void);
void scrollDown(void);
void dispPushButton(void);
void procError(void);
void Dwci_SceneSetEdit32(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void input(void);
void ret_0214ca98(void);
void endScene(void);
void endScene1(void);
void endScene2(void);
void endScene3(void);
void drawSsid(void);
void dispCaret(void);
void procWin(void);
void procWin1(void);
bool isCorrect(void);
void procError(void);
void procError1(void);
void Dwci_SceneSetEditAddress(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void input(void);
bool isOver(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ret_0214d80c(void);
void endScene(void);
void endScene1(void);
void endScene2(void);
void endScene3(void);
void drawAddress(void);
void dispCaret(void);
void procWin(void);
void procWin1(void);
void arrangeAddress(void);
bool isCorrect(void);
void procError(void);
void procError1(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void drawMessage(void);
void procInit(void);
void procInit1(void);
void input(void);
void ret_0214e2b4(void);
void button(void);
void endScene1(void);
void endScene2(void);
void Dwci_SceneSetList(void);
void initGraphics(void);
void calcParam(void);
void procInit(void);
void procInit1(void);
void input(void);
undefined4 inputWinButton(void);
void pushWinButton(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void pushIpAuto(unsigned int param_1);
void pushDnsAuto(unsigned int param_1);
void draw(void);
void endScene1(void);
void endScene2(void);
void drawWindow(void);
void drawColumnChar(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void drawColumnObj(undefined4 param_1,undefined4 param_2);
bool isEnablePush(undefined4 param_1);
void dispObj(int param_1,int param_2,int param_3,undefined4 param_4);
void drawString(int param_1,int param_2);
void drawAddress(undefined1 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void setOffset(void);
unsigned int isPush(void);
int calcColumnIdx(int param_1);
int calcIdxColumn(int param_1);
void taskUp(undefined4 param_1);
void taskDown(undefined4 param_1);
void taskVBlank(void);
void dispFocus(void);
void applyForcus(void);
void applyForcus1(int param_1);
void moveFocus(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void dispPushButton(void);
void taskPushCount(void);
void pushButtonYesNo(void);
undefined4 isCorrect(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void ret_02150a60(void);
void ret_02150a64(void);
void endScene(void);
void endScene1(void);
bool Dwci_IsFold(void);
void Dwci_SceneSetRakuButton1(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void input(void);
void ret_02150cbc(void);
void button(void);
void endScene1(void);
void endScene2(void);
void checkRaku(void);
void procError(void);
bool Dwci_IsFold(void);
void Dwci_SceneSetRakuButton1(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void input(void);
void ret_021510d4(void);
void button(void);
void endScene1(void);
void endScene2(void);
void checkRaku(void);
void procError(void);
void Dwci_SceneSetRakuComplete(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void ret_0215148c(void);
void endScene(void);
void endScene1(void);
bool Dwci_IsFold(void);
void Dwci_SceneSetRakuReady(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void input(void);
void ret_021517a8(void);
void button(void);
void endScene1(void);
void endScene2(void);
void checkRaku(void);
void procError(void);
void Dwci_SceneSetSearch(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void isEnd(void);
void input(void);
void ret_02151d30(void);
void button(void);
void endScene1(void);
void endScene2(void);
void procError(void);
void Dwci_SceneSetSelectAp(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void initGraphics(void);
void initObj(void);
void procInit(void);
void procInit1(void);
void procInit2(void);
void input(void);
void ret_0215232c(void);
void button(void);
void endScene(void);
void endScene1(void);
void endScene2(void);
void dispFocus(void);
void moveFocus(int param_1);
void dispPushClear(void);
void procErase(void);
void dispPush(void);
void Dwci_SceneSetSelectWay(void);
void initGraphics(void);
void procInit(void);
void procInit1(void);
void input(void);
void ret_02153088(void);
void button(void);
void endScene1(void);
void endScene2(void);
void moveFocus(int param_1);
void dispPush(void);
void Dwci_SceneSetTest(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void initAc(void);
void procInit(void);
void procInit1(void);
void ret_02153660(void);
void ret_02153664(void);
void ret_02153668(void);
void endScene(void);
void endScene2(void);
void taskAc(undefined4 param_1);
void Dwci_SceneSetTestCompletet(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void ret_021538e0(void);
void endScene(void);
void endScene1(void);
void wait(void);
void Dwci_SceneSetTestConfirm(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void procScene(void);
void ret_02153c2c(void);
void ret_02153c30(void);
void endScene(void);
void endScene1(void);
void Dwci_SceneSetUsbComplete(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void ret_02153dcc(void);
void endScene(void);
void endScene1(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void input(void);
void ret_021540ac(void);
void button(void);
void endScene1(void);
void endScene2(void);
bool Dwci_IsFold(void);
void Dwci_SceneSetUsbReady1(void);
void initGraphics(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void procInit(void);
void procInit1(void);
void input(void);
void ret_0215446c(void);
void button(void);
void endScene1(void);
void endScene2(void);
void procError(void);
void procBoth(void);
void procBoth1(void);
void Dwci_SCREENlInit(undefined4 param_1);
void Dwci_SCREENlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SCREENlRenew(void);
void Dwci_SCREENlCopy(int param_1,int param_2,int param_3,int param_4);
void taskLoad(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SCREENlCopyPalette(int param_1,int param_2,int param_3,undefined4 param_4);
void taskCopyPltt(undefined4 param_1);
void Dwci_SCREENlSetPalette(undefined4 param_1);
void taskSetPltt(undefined4 param_1);
void Dwci_SBlInit(int param_1,undefined1 param_2,undefined4 param_3,int param_4,int param_5);
void Dwci_SBlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined1 Dwci_SBlGet(void);
undefined1 Dwci_SBlGetState(void);
void disp(int param_1);
void Dwci_SBlEnable(void);
void Dwci_SBlDisable(void);
void taskMain(void);
void moveBar(void);
void playSound(int param_1);
void stepBar(int param_1);
void setBar(void);
int isTrigger(void);
int isTouch(void);
void calcRect(undefined4 param_1,int16_t *param_2);
void disp(int param_1);
void Dwci_SEARCHlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SEARCHlEnd(void);
bool Dwci_SEARCHlBegin(void);
bool startScan(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
bool Dwci_SEARCHlStop(void);
int Dwci_SEARCHlGetApInfo(int *param_1);
void callback(uint16_t *param_1);
void renewInfo(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SETTIGNlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int Dwci_SETTIGNlGet(void);
void Dwci_SETTINGlSetDnsAuto(undefined1 param_1);
void Dwci_SETTINGlSetSsid(undefined4 *param_1);
void Dwci_SETTINGlSetWep(undefined4 *param_1);
void Dwci_SETTINGlGetSsid(undefined4 *param_1);
void Dwci_SETTINGlGetGateway(char *param_1);
void Dwci_SETTINGlGetDnsP(char *param_1);
void Dwci_SETTINGlGetDnsS(char *param_1);
undefined1 Dwci_SETTINGlGetSetType(int param_1);
void Dwci_SETTINGlSetSetting(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SETTINGlSet(void);
void Dwci_SETTINGlSetRaku(undefined4 *param_1);
void Dwci_SETTINGlSetAoss(undefined4 *param_1);
void Dwci_SETTINGlErasePage(int param_1);
void Dwci_SETTINGlEraseAll(void);
void write(unsigned int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SETTINGlConvAddress(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
int ascii2hex(unsigned int param_1);
void Dwci_SndlInit(void);
void Dwci_SndlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_SndlPlay(undefined4 param_1);
void Dwci_SndlSetVolume(undefined4 param_1);
void Dwci_SndlSetPitch(undefined4 param_1,undefined4 param_2);
void Dwci_SndlStop(void);
void Dwci_STEPlBegin(int param_1);
void taskBegin0(undefined4 param_1);
void taskBegin1(undefined4 param_1);
void taskBegin2(undefined4 param_1);
void taskBegin3(undefined4 param_1);
void taskBegin4(undefined4 param_1);
void Dwci_STEPlEnd(void);
void Dwci_STEPlChange(int param_1);
bool Dwci_STEPlGet(void);
void taskEnd0(undefined4 param_1);
void taskEnd1(undefined4 param_1);
void taskEnd2(undefined4 param_1);
void taskEnd3(undefined4 param_1);
void taskEnd4(undefined4 param_1);
bool Dwci_STEPlIsEnd(void);
void Dwci_STEPlChangeScr(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void taskChange(undefined4 param_1);
undefined4 Dwci_USBAPlBegin(undefined4 param_1);
bool startScan(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_USBAPlEnd(void);
void Dwci_USBAPlSetCallback(undefined4 param_1);
void cbWm(int16_t *param_1);
void scanFirst(int param_1);
void scanWait(int param_1);
void taskFirst(undefined4 param_1);
void Dwci_WINlInitEx(undefined4 param_1,int param_2,int param_3,undefined4 param_4,undefined4 param_5);
void Dwci_WINlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int Dwci_WINlGet(void);
bool Dwci_WINlIsInit(void);
void taskV(undefined4 param_1);
void taskMove(undefined4 param_1);
void taskMain(void);
void taskMain1(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void disp(unsigned int param_1);
void dispCell(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void pushButton(int param_1);
void taskEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void taskEnd1(undefined4 param_1);
void taskEnd2(undefined4 param_1);
void taskEnd3(undefined4 param_1);
void Dwci_Mov_Mbp_MemInit(int param_1);
void Dwci_Mov_Mbp_Start(undefined4 param_1,undefined4 param_2);
undefined4 Dwci_Mov_Mbp_RegistFile(int *param_1);
void Dwci_Mov_Mbp_AcceptChild(unsigned int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_Mov_Mbp_KickChild(unsigned int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_Mov_Mbp_StartDownload(unsigned int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_Mov_Mbp_StartDownloadAll(void);
undefined4 Dwci_Mov_Mbp_IsBootableAll(void);
void Dwci_Mov_Mbp_StartRebootAll(void);
void Dwci_Mov_Mbp_Cancel(void);
void Dwci_Mov_Mbp_ChangeState(undefined2 param_1);
undefined2 Dwci_Mov_Mbp_GetState(void);
undefined2 Dwci_Mov_Mbp_GetChildBmp(int param_1);
undefined4 Dwci_Mov_Mbp_GetChildState(unsigned int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int Dwci_Mov_Mbp_GetChildInfo(unsigned int param_1);
undefined2 Dwci_Mov_Mbp_GetPlayerNo(char *param_1);
void Dwci_Mov_WH_MemInit(int param_1);
void Dwci_Mov_WH_ChangeSysState(undefined4 param_1);
void Dwci_Mov_WH_SetError(undefined4 param_1);
undefined4 Dwci_Mov_WH_StateInSetParentParam(void);
void Dwci_Mov_WH_StateOutSetParentParam(int param_1);
undefined4 Dwci_Mov_WH_StateInSetParentWEPKey(void);
void Dwci_Mov_WH_StateOutSetParentWEPKey(int param_1);
undefined4 Dwci_Mov_WH_StateInStartParent(void);
void Dwci_Mov_WH_StateOutStartParent(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_Mov_WH_StateInStartParentMP(void);
void Dwci_Mov_WH_StateOutStartParentMP(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_Mov_WH_StateInStartParentKeyShare(void);
undefined4 Dwci_Mov_WH_StateInEndParentKeyShare(void);
undefined4 Dwci_Mov_WH_StateInEndChildMP(void);
void Dwci_Mov_WH_StateOutEndParentMP(int param_1);
undefined4 Dwci_Mov_WH_StateInEndParent(void);
undefined4 Dwci_Mov_WH_StateInEndChildKeyShare(void);
undefined4 Dwci_Mov_WH_StateInEndChildMP(void);
void Dwci_Mov_WH_StateOutEndChildMP(int param_1);
undefined4 Dwci_Mov_WH_StateInEndChild(void);
undefined4 Dwci_Mov_WH_StateInReset(void);
void Dwci_Mov_WH_StateOutReset(int param_1);
void Dwci_Mov_WH_StateOutEnd(int param_1);
void Dwci_Mov_WH_SetGgid(undefined4 param_1);
undefined2 Dwci_Mov_WH_GetBitmap(void);
undefined4 Dwci_Mov_WH_GetSystemState(void);
undefined4 Dwci_Mov_WH_StartMeasureChannel(void);
undefined2 Dwci_Mov_WH_StateInMeasureChannel(unsigned int param_1);
void Dwci_Mov_WH_StateOutMeasureChannel(int param_1);
void WHi_MeasureChannel(undefined4 param_1,undefined4 param_2);
undefined2 Dwci_Mov_WH_GetMeasureChannel(void);
int SelectChannel(unsigned int param_1);
bool Dwci_Mov_WH_Initialize(void);
undefined4 Dwci_Mov_WH_StateInInitialize(void);
void Dwci_Mov_WH_StateOutInitialize(int param_1);
undefined4 Dwci_Mov_WH_ParentConnect(int param_1,undefined2 param_2,undefined2 param_3);
void Dwci_Mov_WH_GetSharedDataAdr(undefined4 param_1);
undefined4 Dwci_Mov_WH_StepDS(undefined4 param_1);
void Dwci_Mov_WH_Reset(void);
void Dwci_Mov_WH_Finalize(void);
undefined4 Dwci_Mov_WH_End(void);
void Dwci_MovInit(int param_1,undefined4 *param_2);
undefined4 Dwci_MovFinalize(void);
void _Dwci_MovPrepare(void);
undefined4 Dwci_MovStartAdmitChild(void);
undefined4 Dwci_MovStartDownloadandBootChild(void);
void Dwci_MovFramework(void);
void Dwci_MovGetStatus(undefined1 *param_1,undefined4 param_2);
void _Dwci_MovSearchChannel(void);
void _Dwci_MovStartWaitChild(void);
void _Dwci_Mov_WaitandDownloadandBoot_Child(void);
void _Dwci_Mov_ReadyMovUserID(void);
void _Dwci_Mov_MovUserID(void);
void _Dwci_Mov_EraseFlashData(void);
void _Dwci_MovEnd(void);
undefined4 JudgeConnectableChild(int param_1);
void Parent_InitDataShare(void);
void Parent_StepDataShare(undefined2 param_1,undefined2 param_2,undefined4 *param_3);
void Parent_data_receive_progress(void);
undefined2 Parent_get_child_data_kind(void);
void Dwci_ARClInit(void);
void Dwci_ARClEnd(void);
undefined4 userProc(undefined4 param_1,int param_2);
undefined4 cbRead(struct fs_archive *param_1,undefined4 param_2,int param_3,undefined4 param_4);
unsigned int * Dwci_ARClReadEx(char *param_1,unsigned int *param_2,int param_3);
void Dwci_ARClRelease(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
bool cmpBack(char *param_1,char *param_2,int param_3,undefined4 param_4);
void Dwci_CELLlInit(void);
void Dwci_CELLlEnd(void);
int Dwci_CELLlForm(int param_1,int param_2,int param_3,undefined4 param_4);
void Dwci_CELLlDelete(unsigned int param_1);
void Dwci_CELLlSetEffect(int param_1,int param_2,unsigned int param_3,int param_4);
void Dwci_CELLlSetPalette(int param_1,int param_2,int param_3,int param_4);
void Dwci_CELLlSetPosition(int param_1,int param_2,int param_3,unsigned int param_4);
void Dwci_CELLlSetPriority(int param_1,int param_2,int param_3);
void Dwci_CELLlGetPosition(int param_1,int param_2,unsigned int *param_3,unsigned int *param_4);
void Dwci_CEINlRead(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_CEINlRelease(int param_1);
void Dwci_CEINlSet(int param_1,int param_2,int param_3);
undefined4 Dwci_CEINlSetExObj(undefined4 param_1,undefined4 param_2);
undefined4 Dwci_CEINlSetExCell(int param_1,int param_2);
void Dwci_QUElForm(int param_1);
void Dwci_QUElFormEx(int param_1,int param_2,int param_3);
void Dwci_QUElDelete(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_QUElPushBack(uint16_t *param_1,undefined4 param_2);
undefined4 Dwci_QUElPopBack(uint16_t *param_1);
void Dwci_EFFlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined1 Dwci_EFFlCheck(int param_1);
undefined4 Dwci_EFFlFade(int param_1,int param_2,undefined4 param_3,undefined4 param_4);
void taskFade(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_EFFlWait(undefined2 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void taskWait(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
void Dwci_FNTlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_FNTlEnd(void);
int Dwci_FNTlFormEx(int param_1,int param_2,int param_3,undefined4 param_4,undefined4 *param_5,int param_6);
void Dwci_FNTlDelete(int param_1);
int Dwci_FNTlFormBgEx(int param_1,int param_2);
void taskLoad(undefined4 param_1,char *param_2);
void Dwci_FNTlDeleteBg(int param_1);
void Dwci_FNTlDeleteBgLcd(int param_1);
void Dwci_FNTlDraw(int param_1);
void Dwci_FNTlDrawCharEx(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,undefined2 param_5,int param_6);
void Dwci_FNTlDrawStringEx(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4,int param_5,uint16_t *param_6,int param_7);
void Dwci_FNTlDrawRect(int param_1);
void Dwci_FNTlClear(int param_1);
void Dwci_FNTlDisp(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5);
void Dwci_FNTlRenewBg(int param_1);
void Dwci_InputRect(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,undefined2 *param_5);
void Dwci_Coord2Rect(int16_t *param_1,int16_t *param_2,int16_t *param_3);
void Dwci_GXlVisible(int param_1,unsigned int param_2);
void Dwci_GXlInvisible(int param_1,unsigned int param_2);
void Dwci_GXlSetWndPosition(int param_1,int param_2,int16_t *param_3);
void Dwci_GXlSetWndPlane(int param_1,undefined4 param_2,int param_3,int param_4);
void Dwci_HEAPlInit(int8_t *param_1);
void Dwci_HEAPlEnd(void);
void * Dwci_HEAPlAlloc(undefined4 param_1,undefined4 param_2);
int8_t * Dwci_HEAPlAllocEx(unsigned int param_1);
void Dwci_HEAPlFree_(int *param_1);
void Dwci_IPTlInit(void);
void Dwci_IPTlEnd(void);
void Dwci_IPTlRead(void);
void readKey(void);
void readTouch(void);
void Dwci_IPTlCheckFold(void);
void Dwci_ITRlIntr(void);
void Dwci_ITRlEnd(void);
void Dwci_LSTlForm(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_LSTlDelete(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_LSTlErase(int *param_1);
void Dwci_LSTlInsert(int *param_1,int *param_2);
void Dwci_OBJlInit(void);
void taskTransfer(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_OBJlEnd(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_OBJlFormGx(int param_1);
void Dwci_OBJlDelete(unsigned int *param_1);
int Dwci_OBJlGetOam(int param_1,int param_2);
void Dwci_OVRlInit(void);
int Dwci_OVRlAlloc(int param_1,int param_2,int param_3,unsigned int *param_4);
void Dwci_OVRlFree(unsigned int param_1);
int Dwci_STRlNLen(int param_1,int param_2);
void Dwci_ClearVram(void);
void clearVram(void);
void Dwci_SetLedWireless(void);
void Dwci_TSKlInit(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Dwci_TSKlEnd(void);
void Dwci_TSKlAct(int param_1);
void Dwci_TSKlForm(void);
int formTask(int param_1,undefined4 param_2,undefined4 param_3,unsigned int param_4,undefined1 param_5);
void Dwci_TSKlDelete(int param_1,undefined4 param_2);
void deleteTcb(int param_1,int param_2);
void Dwci_TSKlOperate(int param_1,undefined1 param_2);
undefined1 Dwc_Init(undefined4 param_1);
undefined4 Nhttp_Startup(void* *param_1,void* *param_2,undefined4 param_3);
void NHTTPi_CleanupThreadProc(void* *param_1);
undefined4 addHdrList(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int * NHTTPi_getHdrFromList(int *param_1);
int incAscii(char param_1);
undefined4 checkTagPost(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Nhttp_AddHeaderField(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int Nhttp_AddPostDataAscii(int *param_1,undefined4 param_2,undefined4 param_3);
bool Nhttp_SetCAChain(int *param_1,int param_2,int param_3);
int NHTTPi_setReqQueue(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int NHTTPi_findReqQueue(int param_1);
undefined4 NHTTPi_freeReqQueue(void);
void NHTTPi_allFreeReqQueue(void);
undefined4 NHTTPi_initLockReqList(void);
void ret_0215e1f4(void);
undefined4 NHTTPi_createCommThread(undefined4 param_1,int param_2);
void NHTTPi_destroyCommThread(void);
void NHTTPi_kickCommThread(void);
void setupGetcharFromHdrRecvBuf(int param_1,unsigned int param_2,undefined4 *param_3,unsigned int *param_4);
int getcharFromHdrRecvBuf(int param_1,int *param_2,int *param_3);
int NHTTPi_findNextLineHdrRecvBuf(undefined4 param_1,int param_2,int param_3,int *param_4);
int NHTTPi_skipSpaceHdrRecvBuf(undefined4 param_1,int param_2,int param_3);
int NHTTPi_compareTokenN_HdrRecvBuf(undefined4 param_1,int param_2,int param_3,char *param_4,int param_5);
undefined4 NHTTPi_loadFromHdrRecvBuf(int *param_1,int param_2,int param_3,int param_4);
bool NHTTPi_isRecvBufFull(int param_1,unsigned int param_2);
void NHTTPi_RecvBuf(int param_1,undefined4 param_2,int param_3,undefined4 param_4);
undefined4 NHTTPi_RecvBufN(int param_1,undefined4 param_2,int param_3,int param_4);
int Nhttp_CreateRequest(int param_1,unsigned int param_2,undefined4 param_3,int param_4,undefined4 param_5,undefined4 param_6);
void Nhttp_DestroyRequest(int param_1);
void deleteStrList(int *param_1);
undefined4 NHTTPi_destroyRequestObject(int param_1);
int Nhttp_SendRequestAsync(int *param_1);
void NHTTPi_cancelAllRequests(void);
unsigned int NHTTPi_resolveHostname(int param_1,undefined4 param_2,undefined4 param_3,unsigned int param_4);
void Nhttp_DestroyResponse(int param_1);
int NHTTPi_getHeaderValue(int *param_1,undefined4 param_2,int *param_3);
int Nhttp_GetHeaderField(int param_1,undefined4 param_2,undefined4 *param_3,undefined4 param_4);
undefined4 Nhttp_GetBodyAll(int param_1,undefined4 *param_2);
void NHTTPi_SetSSLseed(void);
int NHTTPi_SocOpen(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void NHTTPi_SocCloseWait(undefined4 param_1,int param_2);
undefined4 NHTTPi_SocConnect(int param_1,int param_2,struct socklen_t param_3,unsigned int param_4);
struct ssize_t NHTTPi_SocRecv(int param_1,int param_2,void *param_3,struct size_t param_4,int param_5);
struct ssize_t NHTTPi_SocSend(int param_1,int param_2,void *param_3,struct size_t param_4,int param_5);
void NHTTPi_SocCancel(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
int NHTTPi_strnicmp(char *param_1,char *param_2,int param_3);
void NHTTPi_memclr(int8_t *param_1,unsigned int param_2);
void NHTTPi_memcpy(undefined4 *param_1,undefined4 *param_2,unsigned int param_3);
undefined4 Nhttp_GetProgress(undefined4 *param_1,undefined4 *param_2);
int saveBuf(int param_1,undefined4 param_2,int *param_3,int param_4,int param_5);
int skipLineBuf(undefined4 param_1,undefined4 param_2);
void freeSslConnection(int param_1);
void putSocketToCloseQue(undefined4 param_1,int *param_2);
void clearCloseQue(void);
int NHTTPi_getUrlEncodedSize(char *param_1);
undefined4 NHTTPi_encodeUrlChar(undefined1 *param_1,unsigned int param_2);
int NHTTPi_strToHex(char *param_1,int param_2);
int NHTTPi_strToInt(int param_1,int param_2);
int NHTTPi_intToStr(int param_1,unsigned int param_2);
undefined4 NHTTPi_compareToken(char *param_1,char *param_2);
int NHTTPi_strtonum(char *param_1,int param_2);
undefined4 NHTTPi_memfind(int param_1,int param_2,char *param_3,int param_4);
void Dwci_Ndi_freeAttr(void);
undefined4 setAttr(int param_1,char *param_2);
undefined4 Dwci_NdSetAttr(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int getNchar(char *param_1,char *param_2,int param_3);
int decodeChar(unsigned int param_1);
int Dwci_Ndi_getEncodeLenBASE64(int param_1);
int Dwci_Ndi_encodeBASE64(char *param_1,int param_2,int param_3,unsigned int param_4);
int strAlloc(undefined4 param_1);
undefined4 Dwci_NdStartup(undefined4 param_1,void* *param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5,undefined4 param_6,undefined4 param_7);
void nhttpCleanupCallback(void);
void Dwci_NdCleanupAsync(undefined4 param_1);
undefined4 Dwci_Ndi_getDSdesc(undefined4 param_1,undefined4 param_2);
void Dwci_Ndi_getUserAgent(undefined4 param_1);
void req_callback(int param_1,undefined4 param_2,int param_3,undefined4 param_4);
void freeHttp(undefined4 param_1,undefined4 param_2);
undefined4 setupHttp(int *param_1,int *param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5);
undefined4 runHttp(int *param_1,undefined4 param_2);
bool Dwci_NdGetFileListNumAsync(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_NdGetFileListAsync(undefined4 param_1,undefined4 param_2,int param_3);
undefined4 Dwci_NdGetFileAsync(int param_1,undefined4 param_2,unsigned int param_3,undefined4 param_4);
undefined4 Nhttp_GetProgress(undefined4 *param_1,undefined4 *param_2);
bool Dwci_Ndi_response_count(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
bool Dwci_Ndi_response_contents(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
undefined4 Dwci_Ndi_initLockGlobal(void);
void ret_021626e0(void);
undefined4 Dwci_Ndi_initHttpCallback(void);
void ret_02162734(void);
bool Dwci_Ndi_prepareHttpCallback(undefined4 param_1,int param_2);
void Dwci_Ndi_unprepareHttpCallback(undefined4 param_1,int param_2);
void Dwci_Ndi_kickThread(undefined4 param_1);
void Dwci_Ndi_getMacAddress(undefined4 param_1);
void Dwci_Ndi_memclr(int8_t *param_1,unsigned int param_2);
void Dwci_Ndi_memcpy(undefined4 *param_1,undefined4 *param_2,unsigned int param_3);
int NHTTPi_strToInt(int param_1,int param_2);
int NHTTPi_intToStr(int param_1,unsigned int param_2);
int Dwci_Ndi_hexToStrFigure(int param_1,unsigned int param_2,int param_3);

#endif
